// IDE Config File Export - Generate .cursorrules, Claude rules, Windsurf rules, etc.
// For integration with AI-powered coding tools

import type { DesignStyle } from "../styles";
import type { StyleTokens } from "../styles/tokens";
import { getStyleBySlug } from "../styles";
import { getStyleTokens } from "../styles/tokens-registry";
import { getStyleRecipes } from "../recipes";

export type IdeConfigFormat =
  | "cursorrules"
  | "claude-rules"
  | "windsurf-rules"
  | "generic";

interface StyleData {
  style: DesignStyle;
  tokens: StyleTokens | undefined;
}

function resolveStyleData(slug: string): StyleData | null {
  const style = getStyleBySlug(slug);
  if (!style) return null;
  const tokens = getStyleTokens(slug);
  return { style, tokens };
}

function formatDoList(items: string[]): string {
  return items.map((item) => `- ${item}`).join("\n");
}

function formatTokenReference(tokens: StyleTokens): string {
  const lines: string[] = [];
  lines.push(`- Font (heading): ${tokens.typography.heading}`);
  lines.push(`- Font (body): ${tokens.typography.body}`);
  lines.push(`- Border radius: ${tokens.border.radius}`);
  lines.push(`- Border width: ${tokens.border.width}`);
  lines.push(`- Border color: ${tokens.border.color}`);
  lines.push(`- Shadow (sm): ${tokens.shadow.sm}`);
  lines.push(`- Shadow (md): ${tokens.shadow.md}`);
  lines.push(`- Shadow (lg): ${tokens.shadow.lg}`);
  lines.push(`- Shadow (hover): ${tokens.shadow.hover}`);
  lines.push(`- Spacing (section): ${tokens.spacing.section}`);
  lines.push(`- Spacing (container): ${tokens.spacing.container}`);
  lines.push(`- Spacing (card): ${tokens.spacing.card}`);
  lines.push(`- Transition: ${tokens.interaction.transition}`);
  return lines.join("\n");
}

function formatColorPalette(style: DesignStyle): string {
  const lines: string[] = [];
  lines.push(`- Primary: ${style.colors.primary}`);
  lines.push(`- Secondary: ${style.colors.secondary}`);
  for (let i = 0; i < style.colors.accent.length; i++) {
    lines.push(`- Accent ${i + 1}: ${style.colors.accent[i]}`);
  }
  return lines.join("\n");
}

function formatForbiddenClasses(tokens: StyleTokens, limit = 15): string {
  if (!tokens.forbidden || tokens.forbidden.classes.length === 0) return "";
  const lines: string[] = [];
  for (const cls of tokens.forbidden.classes.slice(0, limit)) {
    const reason = tokens.forbidden.reasons[cls];
    lines.push(`- \`${cls}\`${reason ? `: ${reason}` : ""}`);
  }
  return lines.join("\n");
}

function formatRecipeSummary(slug: string): string {
  const recipes = getStyleRecipes(slug);
  if (!recipes) return "No component recipes available.";

  const lines: string[] = [];
  for (const [id, recipe] of Object.entries(recipes.recipes)) {
    const baseClasses = recipe.skeleton.baseClasses.join(" ");
    lines.push(`### ${recipe.name}`);
    lines.push(`- ID: ${id}`);
    lines.push(`- Base classes: \`${baseClasses}\``);

    const variantEntries = Object.entries(recipe.variants);
    if (variantEntries.length > 0) {
      lines.push("- Variants:");
      for (const [, v] of variantEntries.slice(0, 5)) {
        lines.push(`  - ${v.label}: \`${v.classes.join(" ")}\``);
      }
    }

    if (recipe.states?.hover) {
      lines.push(`- Hover: \`${recipe.states.hover.join(" ")}\``);
    }
    lines.push("");
  }
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Cursor Rules (.cursorrules)
// ---------------------------------------------------------------------------

export function generateCursorRules(slug: string): string | null {
  const data = resolveStyleData(slug);
  if (!data) return null;
  const { style, tokens } = data;

  const sections: string[] = [];

  sections.push(`# Style: ${style.nameEn}
# Generated by StyleKit (https://stylekit.dev)
# Slug: ${style.slug}`);

  sections.push(`## Design Philosophy
${style.philosophy.split("\n\n")[0]}`);

  sections.push(`## Do's
${formatDoList(style.doList)}`);

  sections.push(`## Don'ts
${formatDoList(style.dontList)}`);

  sections.push(`## AI Rules
${style.aiRules}`);

  sections.push(`## Color Palette
${formatColorPalette(style)}`);

  if (tokens) {
    sections.push(`## Token Reference
${formatTokenReference(tokens)}`);

    const forbidden = formatForbiddenClasses(tokens);
    if (forbidden) {
      sections.push(`## Forbidden Classes
${forbidden}`);
    }
  }

  const recipeSummary = formatRecipeSummary(slug);
  if (recipeSummary !== "No component recipes available.") {
    sections.push(`## Component Guidelines
${recipeSummary}`);
  }

  sections.push(`---
Generated by StyleKit · https://stylekit.dev
Style: ${style.name} (${style.nameEn})`);

  return sections.join("\n\n");
}

// ---------------------------------------------------------------------------
// Claude Rules (.claude/rules/{slug}.md)
// ---------------------------------------------------------------------------

export function generateClaudeRules(slug: string): string | null {
  const data = resolveStyleData(slug);
  if (!data) return null;
  const { style, tokens } = data;

  const sections: string[] = [];

  sections.push(`# StyleKit: ${style.nameEn} Design Rules

> ${style.description}`);

  sections.push(`## Philosophy
${style.philosophy.split("\n\n")[0]}`);

  sections.push(`## Rules

### Do
${formatDoList(style.doList)}

### Don't
${formatDoList(style.dontList)}

### AI-Specific Rules
${style.aiRules}`);

  sections.push(`## Colors
${formatColorPalette(style)}`);

  if (tokens) {
    sections.push(`## Design Tokens
${formatTokenReference(tokens)}`);

    const forbidden = formatForbiddenClasses(tokens);
    if (forbidden) {
      sections.push(`## Forbidden Classes
${forbidden}`);
    }
  }

  const recipeSummary = formatRecipeSummary(slug);
  if (recipeSummary !== "No component recipes available.") {
    sections.push(`## Component Recipes
${recipeSummary}`);
  }

  sections.push(`---
Generated by StyleKit · https://stylekit.dev
Style: ${style.name} (${style.nameEn})`);

  return sections.join("\n\n");
}

// ---------------------------------------------------------------------------
// Windsurf Rules
// ---------------------------------------------------------------------------

export function generateWindsurfRules(slug: string): string | null {
  const data = resolveStyleData(slug);
  if (!data) return null;
  const { style, tokens } = data;

  const sections: string[] = [];

  sections.push(`# ${style.nameEn} - Windsurf Rules
# Generated by StyleKit

Style: ${style.slug}
Type: ${style.styleType}`);

  sections.push(`## Design Philosophy
${style.philosophy.split("\n\n")[0]}`);

  sections.push(`## Core Rules
${style.aiRules}`);

  sections.push(`## Do
${formatDoList(style.doList)}`);

  sections.push(`## Don't
${formatDoList(style.dontList)}`);

  sections.push(`## Colors
${formatColorPalette(style)}`);

  if (tokens) {
    sections.push(`## Key Tokens
${formatTokenReference(tokens)}`);

    const forbidden = formatForbiddenClasses(tokens);
    if (forbidden) {
      sections.push(`## Forbidden
${forbidden}`);
    }
  }

  sections.push(`---
Generated by StyleKit · https://stylekit.dev`);

  return sections.join("\n\n");
}

// ---------------------------------------------------------------------------
// Generic Rules (works with any AI tool)
// ---------------------------------------------------------------------------

export function generateGenericRules(slug: string): string | null {
  const data = resolveStyleData(slug);
  if (!data) return null;
  const { style, tokens } = data;

  const sections: string[] = [];

  sections.push(`# ${style.nameEn} Design Style
# Generated by StyleKit (https://stylekit.dev)

${style.description}`);

  sections.push(`## Philosophy
${style.philosophy.split("\n\n")[0]}`);

  sections.push(`## Do
${formatDoList(style.doList)}`);

  sections.push(`## Don't
${formatDoList(style.dontList)}`);

  sections.push(`## AI Generation Rules
${style.aiRules}`);

  sections.push(`## Colors
${formatColorPalette(style)}`);

  if (tokens) {
    sections.push(`## Design Tokens
${formatTokenReference(tokens)}`);

    const forbidden = formatForbiddenClasses(tokens);
    if (forbidden) {
      sections.push(`## Forbidden Classes
${forbidden}`);
    }
  }

  const recipeSummary = formatRecipeSummary(slug);
  if (recipeSummary !== "No component recipes available.") {
    sections.push(`## Component Reference
${recipeSummary}`);
  }

  sections.push(`---
Generated by StyleKit · https://stylekit.dev
Style: ${style.name} (${style.nameEn})`);

  return sections.join("\n\n");
}

// ---------------------------------------------------------------------------
// Unified generator
// ---------------------------------------------------------------------------

export function generateIdeConfig(
  slug: string,
  format: IdeConfigFormat
): string | null {
  switch (format) {
    case "cursorrules":
      return generateCursorRules(slug);
    case "claude-rules":
      return generateClaudeRules(slug);
    case "windsurf-rules":
      return generateWindsurfRules(slug);
    case "generic":
      return generateGenericRules(slug);
  }
}

export function getIdeConfigFilename(
  slug: string,
  format: IdeConfigFormat
): string {
  switch (format) {
    case "cursorrules":
      return ".cursorrules";
    case "claude-rules":
      return `${slug}.md`;
    case "windsurf-rules":
      return `.windsurf-rules`;
    case "generic":
      return `${slug}-rules.md`;
  }
}

export function getIdeConfigMimeType(format: IdeConfigFormat): string {
  switch (format) {
    case "cursorrules":
      return "text/plain";
    case "claude-rules":
    case "windsurf-rules":
    case "generic":
      return "text/markdown";
  }
}
