// Skills Pack Export - Generate SKILL.md for AI tools
// Can be loaded into Cursor, Claude Code, VS Code, etc.

import type { DesignStyle } from "../styles";
import type { StyleTokens } from "../styles/tokens";
import { getStyleRecipes } from "../recipes";
import { getArchetypesForStyle } from "../archetypes";

export interface SkillPackConfig {
  style: DesignStyle;
  tokens?: StyleTokens;
  includeRecipes?: boolean;
  includeArchetypes?: boolean;
  includeExamples?: boolean;
  includeForbidden?: boolean;
}

/**
 * Generate a SKILL.md file for a style
 */
export function generateSkillPack(config: SkillPackConfig): string {
  const {
    style,
    tokens,
    includeRecipes = true,
    includeArchetypes = true,
    includeExamples = true,
    includeForbidden = true,
  } = config;

  const sections: string[] = [];

  // YAML frontmatter
  sections.push(`---
name: ${style.slug}
version: 1.0.0
description: ${style.nameEn} design style for web interfaces
keywords: [${style.keywords.slice(0, 5).join(", ")}]
author: StyleKit
style_type: ${style.styleType || "visual"}
---`);

  // Title and overview
  sections.push(`# ${style.nameEn} Style

## Overview
${style.description}

## Philosophy
${style.philosophy.split("\n\n")[0]}`);

  // Design Tokens
  if (tokens) {
    sections.push(`## Design Tokens

### Border
- Width: \`${tokens.border.width}\`
- Color: \`${tokens.border.color}\`
- Radius: \`${tokens.border.radius}\`

### Shadow
- Small: \`${tokens.shadow.sm}\`
- Medium: \`${tokens.shadow.md}\`
- Large: \`${tokens.shadow.lg}\`
- Hover: \`${tokens.shadow.hover}\`

### Typography
- Heading: \`${tokens.typography.heading}\`
- Body: \`${tokens.typography.body}\`
- Hero: \`${tokens.typography.sizes.hero}\`
- H1: \`${tokens.typography.sizes.h1}\`
- Body: \`${tokens.typography.sizes.body}\`

### Spacing
- Section: \`${tokens.spacing.section}\`
- Container: \`${tokens.spacing.container}\`
- Card: \`${tokens.spacing.card}\`

### Colors
- Primary BG: \`${tokens.colors.background.primary}\`
- Secondary BG: \`${tokens.colors.background.secondary}\`
- Primary Text: \`${tokens.colors.text.primary}\`
- Primary Button: \`${tokens.colors.button.primary}\``);
  }

  // Component Recipes
  if (includeRecipes) {
    const recipes = getStyleRecipes(style.slug);
    if (recipes) {
      sections.push(`## Component Recipes`);

      for (const [, recipe] of Object.entries(recipes.recipes)) {
        const variants = Object.entries(recipe.variants)
          .map(([, v]) => `- ${v.label}: \`${v.classes.join(" ")}\``)
          .join("\n");

        const baseClasses = recipe.skeleton.baseClasses.join(" ");

        sections.push(`### ${recipe.name}
- Base: \`${baseClasses}\`
${variants}`);

        if (recipe.states?.hover) {
          sections.push(`- Hover: \`${recipe.states.hover.join(" ")}\``);
        }
      }
    }
  }

  // Forbidden Patterns
  if (includeForbidden && tokens?.forbidden) {
    const forbiddenList = tokens.forbidden.classes
      .slice(0, 10)
      .map((c) => `- \`${c}\``)
      .join("\n");

    const patternList = tokens.forbidden.patterns
      .slice(0, 5)
      .map((p) => `- Pattern: \`${p}\``)
      .join("\n");

    sections.push(`## Forbidden Patterns
These classes must NEVER be used in ${style.nameEn} style:

${forbiddenList}

${patternList}

### Why:
${Object.entries(tokens.forbidden.reasons)
  .slice(0, 3)
  .map(([cls, reason]) => `- \`${cls}\`: ${reason}`)
  .join("\n")}`);
  }

  // Do's and Don'ts
  sections.push(`## Do's
${style.doList.map((d) => `- ${d}`).join("\n")}

## Don'ts
${style.dontList.map((d) => `- ${d}`).join("\n")}`);

  // Layout Archetypes
  if (includeArchetypes) {
    const archetypes = getArchetypesForStyle(style.slug);
    if (archetypes.length > 0) {
      const archetypeList = archetypes
        .slice(0, 6)
        .map((a) => `- \`${a.id}\`: ${a.description}`)
        .join("\n");

      sections.push(`## Layout Archetypes
${archetypeList}`);
    }
  }

  // Example Usage
  if (includeExamples) {
    sections.push(`## Example Usage

\`\`\`
Generate a landing page with:
- Style: ${style.slug}
- Archetype: landing-hero-centered
- Sections: hero, features, cta, footer
- Components: heading (hero variant), button (primary, lg), card (default)
\`\`\`

### Example Prompts:
${
  style.examplePrompts
    ?.slice(0, 3)
    .map((p) => `- "${p.title}"`)
    .join("\n") || "- Create a landing page in this style"
}`);
  }

  // Footer
  sections.push(`---
Generated by StyleKit · https://stylekit.dev
Style: ${style.name} (${style.nameEn})`);

  return sections.join("\n\n");
}

/**
 * Generate a downloadable SKILL.md file
 */
export function downloadSkillPack(config: SkillPackConfig): void {
  const content = generateSkillPack(config);
  const blob = new Blob([content], { type: "text/markdown" });
  const url = URL.createObjectURL(blob);

  const a = document.createElement("a");
  a.href = url;
  a.download = `${config.style.slug}-SKILL.md`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Get the file info for display
 */
export function getSkillPackFileInfo(style: DesignStyle): {
  name: string;
  filename: string;
  description: string;
  descriptionEn: string;
} {
  return {
    name: "SKILL.md",
    filename: `${style.slug}-SKILL.md`,
    description: "可加载到 Cursor / Claude Code / VS Code 的技能包",
    descriptionEn: "Loadable skill pack for Cursor / Claude Code / VS Code",
  };
}
