// Tailwind Preset Generator
// Generates a Tailwind CSS preset for a style

import type { DesignStyle } from "../styles";
import type { StyleTokens } from "../styles/tokens";

export interface TailwindPreset {
  theme: {
    extend: {
      colors: Record<string, string>;
      fontFamily: Record<string, string[]>;
      borderRadius: Record<string, string>;
      borderWidth: Record<string, string>;
      boxShadow: Record<string, string>;
    };
  };
}

export function generateTailwindPreset(
  style: DesignStyle
): TailwindPreset {
  const colors: Record<string, string> = {
    primary: style.colors.primary,
    secondary: style.colors.secondary,
  };

  style.colors.accent.forEach((color, i) => {
    colors[`accent-${i + 1}`] = color;
  });

  // Base preset
  const preset: TailwindPreset = {
    theme: {
      extend: {
        colors,
        fontFamily: {
          heading: ["Inter", "system-ui", "sans-serif"],
          body: ["Inter", "system-ui", "sans-serif"],
          mono: ["JetBrains Mono", "monospace"],
        },
        borderRadius: {
          none: "0px",
          sm: "2px",
          DEFAULT: "4px",
          md: "6px",
          lg: "8px",
        },
        borderWidth: {
          DEFAULT: "1px",
          "2": "2px",
          "3": "3px",
          "4": "4px",
        },
        boxShadow: {
          brutal: "4px 4px 0px 0px rgba(0,0,0,1)",
          "brutal-md": "6px 6px 0px 0px rgba(0,0,0,1)",
          "brutal-lg": "8px 8px 0px 0px rgba(0,0,0,1)",
        },
      },
    },
  };

  // Style-specific overrides
  if (style.slug.includes("neo-brutalist")) {
    preset.theme.extend.fontFamily = {
      heading: ["Inter", "system-ui", "sans-serif"],
      body: ["JetBrains Mono", "monospace"],
      mono: ["JetBrains Mono", "monospace"],
    };
    preset.theme.extend.boxShadow = {
      brutal: "4px 4px 0px 0px rgba(0,0,0,1)",
      "brutal-md": "6px 6px 0px 0px rgba(0,0,0,1)",
      "brutal-lg": "8px 8px 0px 0px rgba(0,0,0,1)",
      "brutal-pink": "4px 4px 0px 0px rgba(255,0,110,1)",
      "brutal-green": "4px 4px 0px 0px rgba(204,255,0,1)",
    };
  } else if (style.slug === "neumorphism") {
    preset.theme.extend.boxShadow = {
      "neu-sm": "4px 4px 8px #bebebe, -4px -4px 8px #ffffff",
      neu: "6px 6px 12px #bebebe, -6px -6px 12px #ffffff",
      "neu-lg": "10px 10px 20px #bebebe, -10px -10px 20px #ffffff",
      "neu-inset": "inset 4px 4px 8px #bebebe, inset -4px -4px 8px #ffffff",
    };
  } else if (style.slug === "glassmorphism") {
    preset.theme.extend.boxShadow = {
      glass: "0 8px 32px 0 rgba(31, 38, 135, 0.37)",
      "glass-lg": "0 12px 48px 0 rgba(31, 38, 135, 0.5)",
    };
  }

  return preset;
}

export function generateTailwindPresetJS(
  style: DesignStyle,
  tokens?: StyleTokens
): string {
  void tokens;
  const preset = generateTailwindPreset(style);

  return `// ${style.name} (${style.nameEn}) Tailwind CSS Preset
// Generated by StyleKit

/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: ${JSON.stringify(preset.theme.extend, null, 6).replace(/"([^"]+)":/g, "$1:")},
  },
};
`;
}
