import { describe, it, expect } from "vitest";
import {
  generateTailwindPreset,
  generateTailwindPresetJS,
} from "@/lib/export/tailwind-preset";
import { getStyleBySlug } from "@/lib/styles";

// ---------------------------------------------------------------------------
// generateTailwindPreset
// ---------------------------------------------------------------------------

describe("generateTailwindPreset", () => {
  it("returns a valid preset structure for neo-brutalist", () => {
    const style = getStyleBySlug("neo-brutalist")!;
    const preset = generateTailwindPreset(style);
    expect(preset).toHaveProperty("theme");
    expect(preset.theme).toHaveProperty("extend");
    expect(preset.theme.extend).toHaveProperty("colors");
    expect(preset.theme.extend).toHaveProperty("fontFamily");
    expect(preset.theme.extend).toHaveProperty("borderRadius");
    expect(preset.theme.extend).toHaveProperty("borderWidth");
    expect(preset.theme.extend).toHaveProperty("boxShadow");
  });

  it("includes primary and secondary colors from the style", () => {
    const style = getStyleBySlug("neo-brutalist")!;
    const preset = generateTailwindPreset(style);
    expect(preset.theme.extend.colors.primary).toBe(style.colors.primary);
    expect(preset.theme.extend.colors.secondary).toBe(style.colors.secondary);
  });

  it("includes accent colors indexed from 1", () => {
    const style = getStyleBySlug("neo-brutalist")!;
    const preset = generateTailwindPreset(style);
    if (style.colors.accent.length > 0) {
      expect(preset.theme.extend.colors["accent-1"]).toBe(
        style.colors.accent[0]
      );
    }
  });

  it("applies neo-brutalist specific shadow overrides", () => {
    const style = getStyleBySlug("neo-brutalist")!;
    const preset = generateTailwindPreset(style);
    expect(preset.theme.extend.boxShadow).toHaveProperty("brutal-pink");
    expect(preset.theme.extend.boxShadow).toHaveProperty("brutal-green");
  });

  it("applies neumorphism specific shadow overrides", () => {
    const style = getStyleBySlug("neumorphism")!;
    const preset = generateTailwindPreset(style);
    expect(preset.theme.extend.boxShadow).toHaveProperty("neu");
    expect(preset.theme.extend.boxShadow).toHaveProperty("neu-inset");
  });

  it("applies glassmorphism specific shadow overrides", () => {
    const style = getStyleBySlug("glassmorphism")!;
    const preset = generateTailwindPreset(style);
    expect(preset.theme.extend.boxShadow).toHaveProperty("glass");
    expect(preset.theme.extend.boxShadow).toHaveProperty("glass-lg");
  });

  it("uses default shadows for styles without overrides", () => {
    const style = getStyleBySlug("minimalist-flat")!;
    const preset = generateTailwindPreset(style);
    expect(preset.theme.extend.boxShadow).toHaveProperty("brutal");
  });
});

// ---------------------------------------------------------------------------
// generateTailwindPresetJS
// ---------------------------------------------------------------------------

describe("generateTailwindPresetJS", () => {
  it("returns a non-empty string", () => {
    const style = getStyleBySlug("neo-brutalist")!;
    const js = generateTailwindPresetJS(style);
    expect(typeof js).toBe("string");
    expect(js.length).toBeGreaterThan(0);
  });

  it("contains module.exports", () => {
    const style = getStyleBySlug("neo-brutalist")!;
    const js = generateTailwindPresetJS(style);
    expect(js).toContain("module.exports");
  });

  it("contains Generated by StyleKit header", () => {
    const style = getStyleBySlug("neo-brutalist")!;
    const js = generateTailwindPresetJS(style);
    expect(js).toContain("Generated by StyleKit");
  });

  it("contains the style name in the header", () => {
    const style = getStyleBySlug("neo-brutalist")!;
    const js = generateTailwindPresetJS(style);
    expect(js).toContain(style.nameEn);
  });

  it("includes theme.extend structure", () => {
    const style = getStyleBySlug("glassmorphism")!;
    const js = generateTailwindPresetJS(style);
    expect(js).toContain("theme:");
    expect(js).toContain("extend:");
  });
});
