import type { StylePreviewComponents } from "./types";

type StylePreviewLoader = () => Promise<StylePreviewComponents>;

const stylePreviewLoaders: Record<string, StylePreviewLoader> = {
  // Style preview loaders
  "neo-brutalist": () => import("./styles/neo-brutalist").then((module) => module.default),
  "neo-brutalist-soft": () => import("./styles/neo-brutalist-soft").then((module) => module.default),
  "neo-brutalist-playful": () => import("./styles/neo-brutalist-playful").then((module) => module.default),
  "editorial": () => import("./styles/editorial").then((module) => module.default),
  "neumorphism": () => import("./styles/neumorphism").then((module) => module.default),
  "glassmorphism": () => import("./styles/glassmorphism").then((module) => module.default),
  "bento-grid": () => import("./styles/bento-grid").then((module) => module.default),
  "corporate-clean": () => import("./styles/corporate-clean").then((module) => module.default),
  "minimalist-flat": () => import("./styles/minimalist-flat").then((module) => module.default),
  "soft-ui": () => import("./styles/soft-ui").then((module) => module.default),
  "cyberpunk-neon": () => import("./styles/cyberpunk-neon").then((module) => module.default),
  "natural-organic": () => import("./styles/natural-organic").then((module) => module.default),
  "modern-gradient": () => import("./styles/modern-gradient").then((module) => module.default),
  "retro-vintage": () => import("./styles/retro-vintage").then((module) => module.default),
  "dark-mode": () => import("./styles/dark-mode").then((module) => module.default),
  "macos-vibrancy": () => import("./styles/macos-vibrancy").then((module) => module.default),
  "geometric-bold": () => import("./styles/geometric-bold").then((module) => module.default),
  "masonry-flow": () => import("./styles/masonry-flow").then((module) => module.default),
  "split-screen": () => import("./styles/split-screen").then((module) => module.default),
  "full-page-scroll": () => import("./styles/full-page-scroll").then((module) => module.default),
  "timeline-vertical": () => import("./styles/timeline-vertical").then((module) => module.default),
  "card-stack": () => import("./styles/card-stack").then((module) => module.default),
  "sidebar-fixed": () => import("./styles/sidebar-fixed").then((module) => module.default),
  "magazine-grid": () => import("./styles/magazine-grid").then((module) => module.default),
  "hero-fullscreen": () => import("./styles/hero-fullscreen").then((module) => module.default),
  "claymorphism": () => import("./styles/claymorphism").then((module) => module.default),
  "notion-style": () => import("./styles/notion-style").then((module) => module.default),
  "stripe-style": () => import("./styles/stripe-style").then((module) => module.default),
  "apple-style": () => import("./styles/apple-style").then((module) => module.default),
  "pixel-art": () => import("./styles/pixel-art").then((module) => module.default),
  "vaporwave": () => import("./styles/vaporwave").then((module) => module.default),
  "y2k": () => import("./styles/y2k").then((module) => module.default),
  "memphis": () => import("./styles/memphis").then((module) => module.default),
  "art-deco": () => import("./styles/art-deco").then((module) => module.default),
  "bauhaus": () => import("./styles/bauhaus").then((module) => module.default),
  "synthwave": () => import("./styles/synthwave").then((module) => module.default),
  "skeuomorphism": () => import("./styles/skeuomorphism").then((module) => module.default),
  "swiss-style": () => import("./styles/swiss-style").then((module) => module.default),
  "ghibli-style": () => import("./styles/ghibli-style").then((module) => module.default),
  "material-design": () => import("./styles/material-design").then((module) => module.default),
  "fluent-design": () => import("./styles/fluent-design").then((module) => module.default),
  "comic-style": () => import("./styles/comic-style").then((module) => module.default),
  "sketch-style": () => import("./styles/sketch-style").then((module) => module.default),
  "watercolor-style": () => import("./styles/watercolor-style").then((module) => module.default),
  "f-pattern-layout": () => import("./styles/f-pattern-layout").then((module) => module.default),
  "z-pattern-layout": () => import("./styles/z-pattern-layout").then((module) => module.default),
  "holy-grail-layout": () => import("./styles/holy-grail-layout").then((module) => module.default),
  "dashboard-layout": () => import("./styles/dashboard-layout").then((module) => module.default),
  "art-nouveau": () => import("./styles/art-nouveau").then((module) => module.default),
  "surrealism": () => import("./styles/surrealism").then((module) => module.default),
  "ukiyo-e-digital": () => import("./styles/ukiyo-e-digital").then((module) => module.default),
  "gothic": () => import("./styles/gothic").then((module) => module.default),
  "outrun": () => import("./styles/outrun").then((module) => module.default),
  "dark-academia": () => import("./styles/dark-academia").then((module) => module.default),
  "cottagecore": () => import("./styles/cottagecore").then((module) => module.default),
  "risograph": () => import("./styles/risograph").then((module) => module.default),
  "mecha": () => import("./styles/mecha").then((module) => module.default),
  "gothic-lolita": () => import("./styles/gothic-lolita").then((module) => module.default),
  "cyber-chinese": () => import("./styles/cyber-chinese").then((module) => module.default),
  "acid-graphics": () => import("./styles/acid-graphics").then((module) => module.default),
  "hand-drawn-doodle": () => import("./styles/hand-drawn-doodle").then((module) => module.default),
  "swiss-poster": () => import("./styles/swiss-poster").then((module) => module.default),
  "watercolor-art": () => import("./styles/watercolor-art").then((module) => module.default),
  "immersive-photo": () => import("./styles/immersive-photo").then((module) => module.default),
  "impressionist-oil": () => import("./styles/impressionist-oil").then((module) => module.default),
  "collage-art": () => import("./styles/collage-art").then((module) => module.default),
  "glitch-art": () => import("./styles/glitch-art").then((module) => module.default),
  "visual-novel": () => import("./styles/visual-novel").then((module) => module.default),
  "shoujo-manga": () => import("./styles/shoujo-manga").then((module) => module.default),
  "cyber-anime": () => import("./styles/cyber-anime").then((module) => module.default),
  "pixel-anime": () => import("./styles/pixel-anime").then((module) => module.default),
  "japanese-fresh": () => import("./styles/japanese-fresh").then((module) => module.default),
  "neon-samurai": () => import("./styles/neon-samurai").then((module) => module.default),
  "magic-circle": () => import("./styles/magic-circle").then((module) => module.default),
  "cyber-wafuu": () => import("./styles/cyber-wafuu").then((module) => module.default),
  "steampunk": () => import("./styles/steampunk").then((module) => module.default),
  "pop-art": () => import("./styles/pop-art").then((module) => module.default),
  "solarpunk": () => import("./styles/solarpunk").then((module) => module.default),
  "jrpg": () => import("./styles/jrpg").then((module) => module.default),
  "asymmetric-grid": () => import("./styles/asymmetric-grid").then((module) => module.default),
  "parallax-sections": () => import("./styles/parallax-sections").then((module) => module.default),
  "warm-dashboard": () => import("./styles/warm-dashboard").then((module) => module.default),
  "neon-gradient": () => import("./styles/neon-gradient").then((module) => module.default),
  "liquid-glass": () => import("./styles/liquid-glass").then((module) => module.default),
  "scandinavian": () => import("./styles/scandinavian").then((module) => module.default),
  "cinematic-video-hero": () => import("./styles/cinematic-video-hero").then((module) => module.default),
  "cel-shading": () => import("./styles/cel-shading").then((module) => module.default),
  "wabi-sabi": () => import("./styles/wabi-sabi").then((module) => module.default),
  "scrollytelling": () => import("./styles/scrollytelling").then((module) => module.default),
  "sci-fi-hud": () => import("./styles/sci-fi-hud").then((module) => module.default),
  "kawaii-minimal": () => import("./styles/kawaii-minimal").then((module) => module.default),
  "film-noir": () => import("./styles/film-noir").then((module) => module.default),
  "arcade-crt": () => import("./styles/arcade-crt").then((module) => module.default),
  "frutiger-aero": () => import("./styles/frutiger-aero").then((module) => module.default),
  "anti-design": () => import("./styles/anti-design").then((module) => module.default),
  "holographic": () => import("./styles/holographic").then((module) => module.default),
  "generative-art": () => import("./styles/generative-art").then((module) => module.default),
  "particle": () => import("./styles/particle").then((module) => module.default),
  "vhs-aesthetic": () => import("./styles/vhs-aesthetic").then((module) => module.default),
  "terracotta": () => import("./styles/terracotta").then((module) => module.default),
  "brutalist-web": () => import("./styles/brutalist-web").then((module) => module.default),
  "mid-century-modern": () => import("./styles/mid-century-modern").then((module) => module.default),
  "constructivism": () => import("./styles/constructivism").then((module) => module.default),
  "op-art": () => import("./styles/op-art").then((module) => module.default),
  "islamic-geometric": () => import("./styles/islamic-geometric").then((module) => module.default),
  "indian-festive": () => import("./styles/indian-festive").then((module) => module.default),
  "african-textile": () => import("./styles/african-textile").then((module) => module.default),
  "kinetic-typography": () => import("./styles/kinetic-typography").then((module) => module.default),
  "korean-minimal": () => import("./styles/korean-minimal").then((module) => module.default),
  "parallax-editorial": () => import("./styles/parallax-editorial").then((module) => module.default),
  "pastel-goth": () => import("./styles/pastel-goth").then((module) => module.default),
  "maximalism": () => import("./styles/maximalism").then((module) => module.default),
  "medieval-manuscript": () => import("./styles/medieval-manuscript").then((module) => module.default),
  "graffiti-street": () => import("./styles/graffiti-street").then((module) => module.default),
  "marble-luxury": () => import("./styles/marble-luxury").then((module) => module.default),
  "victorian-botanical": () => import("./styles/victorian-botanical").then((module) => module.default),
  "cubism": () => import("./styles/cubism").then((module) => module.default),
  "tropical-paradise": () => import("./styles/tropical-paradise").then((module) => module.default),
  "github-style": () => import("./styles/github-style").then((module) => module.default),
  "witchcore": () => import("./styles/witchcore").then((module) => module.default),
  "neon-tokyo": () => import("./styles/neon-tokyo").then((module) => module.default),
  "paper-craft": () => import("./styles/paper-craft").then((module) => module.default),
  "blueprint": () => import("./styles/blueprint").then((module) => module.default),
  "zen-garden": () => import("./styles/zen-garden").then((module) => module.default),
  "ink-wash": () => import("./styles/ink-wash").then((module) => module.default),
  "monochrome": () => import("./styles/monochrome").then((module) => module.default),
  "dopamine-design": () => import("./styles/dopamine-design").then((module) => module.default),
  "linear-style": () => import("./styles/linear-style").then((module) => module.default),
  "shopify-clean": () => import("./styles/shopify-clean").then((module) => module.default),
  "luxury-retail": () => import("./styles/luxury-retail").then((module) => module.default),
  "fresh-market": () => import("./styles/fresh-market").then((module) => module.default),
  "data-dense": () => import("./styles/data-dense").then((module) => module.default),
  "oversized-typography": () => import("./styles/oversized-typography").then((module) => module.default),
  "developer-terminal": () => import("./styles/developer-terminal").then((module) => module.default),
  "horizontal-gallery": () => import("./styles/horizontal-gallery").then((module) => module.default),
  "latex-paper": () => import("./styles/latex-paper").then((module) => module.default),
  "distill-style": () => import("./styles/distill-style").then((module) => module.default),
  "gallery-dark": () => import("./styles/gallery-dark").then((module) => module.default),
  "studio-bold": () => import("./styles/studio-bold").then((module) => module.default),
  "warm-organic": () => import("./styles/warm-organic").then((module) => module.default),
  "launch-keynote": () => import("./styles/launch-keynote").then((module) => module.default),
  "luxe-lookbook": () => import("./styles/luxe-lookbook").then((module) => module.default),
  "shader-gradient": () => import("./styles/shader-gradient").then((module) => module.default),
  // End style preview loaders
};

const previewPromises = new Map<string, Promise<StylePreviewComponents>>();
let allPreviewsPromise: Promise<unknown> | null = null;

export const stylePreviewSlugs = Object.freeze([
  // Style preview slugs
  "neo-brutalist",
  "neo-brutalist-soft",
  "neo-brutalist-playful",
  "editorial",
  "neumorphism",
  "glassmorphism",
  "bento-grid",
  "corporate-clean",
  "minimalist-flat",
  "soft-ui",
  "cyberpunk-neon",
  "natural-organic",
  "modern-gradient",
  "retro-vintage",
  "dark-mode",
  "macos-vibrancy",
  "geometric-bold",
  "masonry-flow",
  "split-screen",
  "full-page-scroll",
  "timeline-vertical",
  "card-stack",
  "sidebar-fixed",
  "magazine-grid",
  "hero-fullscreen",
  "claymorphism",
  "notion-style",
  "stripe-style",
  "apple-style",
  "pixel-art",
  "vaporwave",
  "y2k",
  "memphis",
  "art-deco",
  "bauhaus",
  "synthwave",
  "skeuomorphism",
  "swiss-style",
  "ghibli-style",
  "material-design",
  "fluent-design",
  "comic-style",
  "sketch-style",
  "watercolor-style",
  "f-pattern-layout",
  "z-pattern-layout",
  "holy-grail-layout",
  "dashboard-layout",
  "art-nouveau",
  "surrealism",
  "ukiyo-e-digital",
  "gothic",
  "outrun",
  "dark-academia",
  "cottagecore",
  "risograph",
  "mecha",
  "gothic-lolita",
  "cyber-chinese",
  "acid-graphics",
  "hand-drawn-doodle",
  "swiss-poster",
  "watercolor-art",
  "immersive-photo",
  "impressionist-oil",
  "collage-art",
  "glitch-art",
  "visual-novel",
  "shoujo-manga",
  "cyber-anime",
  "pixel-anime",
  "japanese-fresh",
  "neon-samurai",
  "magic-circle",
  "cyber-wafuu",
  "steampunk",
  "pop-art",
  "solarpunk",
  "jrpg",
  "asymmetric-grid",
  "parallax-sections",
  "warm-dashboard",
  "neon-gradient",
  "liquid-glass",
  "scandinavian",
  "cinematic-video-hero",
  "cel-shading",
  "wabi-sabi",
  "scrollytelling",
  "sci-fi-hud",
  "kawaii-minimal",
  "film-noir",
  "arcade-crt",
  "frutiger-aero",
  "anti-design",
  "holographic",
  "generative-art",
  "particle",
  "vhs-aesthetic",
  "terracotta",
  "brutalist-web",
  "mid-century-modern",
  "constructivism",
  "op-art",
  "islamic-geometric",
  "indian-festive",
  "african-textile",
  "kinetic-typography",
  "korean-minimal",
  "parallax-editorial",
  "pastel-goth",
  "maximalism",
  "medieval-manuscript",
  "graffiti-street",
  "marble-luxury",
  "victorian-botanical",
  "cubism",
  "tropical-paradise",
  "github-style",
  "witchcore",
  "neon-tokyo",
  "paper-craft",
  "blueprint",
  "zen-garden",
  "ink-wash",
  "monochrome",
  "dopamine-design",
  "linear-style",
  "shopify-clean",
  "luxury-retail",
  "fresh-market",
  "data-dense",
  "oversized-typography",
  "developer-terminal",
  "horizontal-gallery",
  "latex-paper",
  "distill-style",
  "gallery-dark",
  "studio-bold",
  "warm-organic",
  "launch-keynote",
  "luxe-lookbook",
  "shader-gradient",
  // End style preview slugs
]);

export function loadStylePreview(
  styleSlug: string,
): Promise<StylePreviewComponents | null> {
  const loader = stylePreviewLoaders[styleSlug];
  if (!loader) {
    return Promise.resolve(null);
  }

  const cached = previewPromises.get(styleSlug);
  if (cached) {
    return cached;
  }

  const previewPromise = loader();
  previewPromises.set(styleSlug, previewPromise);
  return previewPromise;
}

/**
 * Warms every approved preview for the compare-only visual baseline route.
 * Normal catalog traffic stays viewport-driven and never calls this helper.
 */
export function preloadStylePreviews(): Promise<unknown> {
  if (!allPreviewsPromise) {
    allPreviewsPromise = Promise.all(
      stylePreviewSlugs.map((styleSlug) => loadStylePreview(styleSlug)),
    );
  }
  return allPreviewsPromise;
}
