/**
 * Lightweight animation metadata module
 *
 * Contains ONLY metadata - no code snippets or heavy fields.
 * Import this in client components to avoid bundling full animation definitions.
 *
 * For full animation data (including codeSnippets), use:
 * import { getAnimationBySlug } from "@/lib/animations"
 */

import type { AnimationMeta } from "./types";

export const animationsMeta: AnimationMeta[] = [
  {
    slug: "fade-in-up",
    name: "淡入上滑",
    nameEn: "Fade In Up",
    description: "元素从下方淡入并向上滑动，最常见的入场动画之一。",
    category: "entrance",
    tags: ["fade", "slide", "entrance", "mount"],
    trigger: "on-mount",
    difficulty: "beginner",
    duration: "600ms",
    keywords: ["fade in", "slide up", "entrance", "appear", "mount animation"],
  },
  {
    slug: "scale-in",
    name: "缩放淡入",
    nameEn: "Scale In",
    description: "元素从缩小状态放大至原始尺寸并淡入，适合卡片、弹窗等组件入场。",
    category: "entrance",
    tags: ["scale", "zoom", "entrance", "mount"],
    trigger: "on-mount",
    difficulty: "beginner",
    duration: "400ms",
    keywords: ["scale", "zoom in", "entrance", "grow", "expand"],
  },
  {
    slug: "hover-lift",
    name: "悬浮抬升",
    nameEn: "Hover Lift",
    description: "鼠标悬停时元素向上移动并加深阴影，营造悬浮立体感。",
    category: "hover",
    tags: ["hover", "lift", "shadow", "interactive"],
    trigger: "on-hover",
    difficulty: "beginner",
    duration: "200ms",
    keywords: ["hover", "lift", "float", "shadow", "card hover", "elevation"],
  },
  {
    slug: "typewriter",
    name: "打字机效果",
    nameEn: "Typewriter",
    description: "文字逐字显现并带有闪烁光标，模拟打字机输入效果。",
    category: "text",
    tags: ["text", "typewriter", "cursor", "sequential"],
    trigger: "on-mount",
    difficulty: "intermediate",
    duration: "3s",
    keywords: ["typewriter", "typing", "text reveal", "cursor blink", "sequential text"],
  },
  {
    slug: "skeleton-pulse",
    name: "骨架屏脉冲",
    nameEn: "Skeleton Pulse",
    description: "骨架屏加载占位符的脉冲闪烁效果，提示用户内容正在加载中。",
    category: "loading",
    tags: ["loading", "skeleton", "pulse", "placeholder"],
    trigger: "continuous",
    difficulty: "beginner",
    duration: "2s",
    keywords: ["skeleton", "loading", "pulse", "shimmer", "placeholder", "content loading"],
  },
  {
    slug: "fade-in-down",
    name: "淡入下滑",
    nameEn: "Fade In Down",
    description: "元素从上方淡入并向下滑动，常用于导航栏、下拉菜单入场。",
    category: "entrance",
    tags: ["fade", "slide", "entrance", "dropdown"],
    trigger: "on-mount",
    difficulty: "beginner",
    duration: "600ms",
    keywords: ["fade in", "slide down", "entrance", "dropdown", "navbar"],
  },
  {
    slug: "slide-in-left",
    name: "左侧滑入",
    nameEn: "Slide In Left",
    description: "元素从左侧滑入视口，适合侧边栏、抽屉菜单等组件。",
    category: "entrance",
    tags: ["slide", "entrance", "horizontal", "sidebar"],
    trigger: "on-mount",
    difficulty: "beginner",
    duration: "500ms",
    keywords: ["slide", "left", "entrance", "sidebar", "drawer", "panel"],
  },
  {
    slug: "hover-glow",
    name: "悬浮发光",
    nameEn: "Hover Glow",
    description: "鼠标悬停时元素边框发出柔和光晕，适合 CTA 按钮和交互卡片。",
    category: "hover",
    tags: ["hover", "glow", "border", "interactive"],
    trigger: "on-hover",
    difficulty: "beginner",
    duration: "300ms",
    keywords: ["hover", "glow", "border glow", "neon", "CTA", "button hover"],
  },
  {
    slug: "scroll-reveal",
    name: "滚动显现",
    nameEn: "Scroll Reveal",
    description: "元素进入视口时淡入显现，利用 IntersectionObserver 实现滚动触发。",
    category: "scroll",
    tags: ["scroll", "reveal", "intersection", "viewport"],
    trigger: "on-scroll",
    difficulty: "intermediate",
    duration: "600ms",
    keywords: ["scroll", "reveal", "viewport", "intersection observer", "lazy", "on-scroll"],
    playgroundMode: "scroll-driven",
  },
  {
    slug: "parallax-float",
    name: "视差浮动",
    nameEn: "Parallax Float",
    description: "元素随滚动以不同速率移动，产生深度视差效果，增强页面层次感。",
    category: "scroll",
    tags: ["scroll", "parallax", "depth", "float"],
    trigger: "on-scroll",
    difficulty: "intermediate",
    duration: "continuous",
    keywords: ["parallax", "float", "depth", "scroll speed", "layers", "3D"],
    playgroundMode: "scroll-driven",
  },
  {
    slug: "text-gradient-flow",
    name: "文字渐变流动",
    nameEn: "Text Gradient Flow",
    description: "文字颜色以渐变方式持续流动变化，吸引注意力的标题效果。",
    category: "text",
    tags: ["text", "gradient", "flow", "color", "continuous"],
    trigger: "continuous",
    difficulty: "beginner",
    duration: "3s",
    keywords: ["text gradient", "gradient flow", "animated text", "color shift", "headline"],
  },
  {
    slug: "spinner-dots",
    name: "三点弹跳加载",
    nameEn: "Spinner Dots",
    description: "三个圆点依次弹跳的加载指示器，轻量且易于实现。",
    category: "loading",
    tags: ["loading", "spinner", "dots", "bounce"],
    trigger: "continuous",
    difficulty: "beginner",
    duration: "1.4s",
    keywords: ["spinner", "dots", "loading", "bounce", "indicator", "three dots"],
  },
  {
    slug: "background-gradient-shift",
    name: "背景渐变流动",
    nameEn: "Background Gradient Shift",
    description: "背景渐变颜色持续缓慢流动变化，营造动态氛围感。",
    category: "background",
    tags: ["background", "gradient", "ambient", "continuous"],
    trigger: "continuous",
    difficulty: "beginner",
    duration: "8s",
    keywords: ["background", "gradient", "shift", "ambient", "flow", "color change"],
  },
  {
    slug: "stagger-children",
    name: "子元素错开动画",
    nameEn: "Stagger Children",
    description: "子元素依次错开执行入场动画，通过延迟差营造流畅的序列感。",
    category: "micro-interaction",
    tags: ["stagger", "sequence", "children", "cascade", "list"],
    trigger: "on-mount",
    difficulty: "intermediate",
    duration: "500ms",
    keywords: ["stagger", "cascade", "sequence", "children", "list animation", "delay"],
  },
  {
    slug: "blur-in",
    name: "模糊到清晰",
    nameEn: "Blur In",
    description: "元素从模糊状态逐渐变清晰并淡入，营造柔和的过渡入场效果。",
    category: "transition",
    tags: ["blur", "focus", "entrance", "transition"],
    trigger: "on-mount",
    difficulty: "beginner",
    duration: "500ms",
    keywords: ["blur", "focus", "sharp", "entrance", "transition", "soft"],
  },
  {
    slug: "spotlight-card",
    name: "聚光灯卡片",
    nameEn: "Spotlight Card",
    description: "鼠标在卡片上方移动时，呈现手电筒照亮卡片局部的光影跟随效果。",
    category: "pointer",
    tags: ["hover", "spotlight", "glow", "mouse-tracking"],
    trigger: "on-hover",
    difficulty: "advanced",
    duration: "continuous",
    keywords: ["spotlight", "mouse tracking", "glow", "card effect", "lighting"],
    playgroundMode: "js-driven",
    intensity: "low",
    input: "pointer-fine",
  },
  {
    slug: "magnetic-hover",
    name: "磁吸悬浮",
    nameEn: "Magnetic Hover",
    description: "鼠标靠近目标元素时，元素会像被磁铁吸引一样向鼠标指针方向产生弹性位移。",
    category: "pointer",
    tags: ["hover", "magnetic", "physics", "interactive"],
    trigger: "on-hover",
    difficulty: "intermediate",
    duration: "continuous",
    keywords: ["magnetic", "spring", "button hover", "physics", "attract"],
    playgroundMode: "js-driven",
    intensity: "medium",
    input: "pointer-fine",
  },
  {
    slug: "bounce-in",
    name: "弹性入场",
    nameEn: "Bounce In",
    description: "元素以弹性缩放方式入场，从小尺寸弹跳过冲后稳定在原始大小，充满活力感。",
    category: "entrance",
    tags: ["bounce", "scale", "entrance", "elastic", "mount"],
    trigger: "on-mount",
    difficulty: "beginner",
    duration: "600ms",
    keywords: ["bounce", "elastic", "spring", "entrance", "scale", "overshoot"],
  },
  {
    slug: "slide-in-right",
    name: "右侧滑入",
    nameEn: "Slide In Right",
    description: "元素从右侧滑入视口，适合侧面板、抽屉菜单和分屏布局的入场效果。",
    category: "entrance",
    tags: ["slide", "entrance", "horizontal", "panel"],
    trigger: "on-mount",
    difficulty: "beginner",
    duration: "500ms",
    keywords: ["slide", "right", "entrance", "panel", "drawer", "horizontal"],
  },
  {
    slug: "rotate-in",
    name: "旋转入场",
    nameEn: "Rotate In",
    description: "元素从反向旋转并透明的状态旋转至正位并淡入，适合图标和趣味性入场。",
    category: "entrance",
    tags: ["rotate", "spin", "entrance", "mount"],
    trigger: "on-mount",
    difficulty: "intermediate",
    duration: "500ms",
    keywords: ["rotate", "spin", "entrance", "turn", "twist", "icon animation"],
  },
  {
    slug: "shake",
    name: "抖动提示",
    nameEn: "Shake",
    description: "元素在水平方向快速抖动，常用于表单校验失败或错误提示的视觉反馈。",
    category: "micro-interaction",
    tags: ["shake", "error", "feedback", "attention", "click"],
    trigger: "on-click",
    difficulty: "beginner",
    duration: "500ms",
    keywords: ["shake", "vibrate", "error", "validation", "feedback", "attention"],
  },
  {
    slug: "flip-card",
    name: "3D 卡片翻转",
    nameEn: "Flip Card",
    description: "卡片沿 Y 轴进行 3D 翻转，显示背面内容，需要透视容器和 backface-visibility 控制。",
    category: "hover",
    tags: ["flip", "3d", "card", "hover", "perspective"],
    trigger: "on-hover",
    difficulty: "advanced",
    duration: "600ms",
    keywords: ["flip", "card", "3d", "rotate", "perspective", "backface", "two-sided"],
  },
  {
    slug: "ripple-click",
    name: "涟漪点击",
    nameEn: "Ripple Click",
    description: "点击时从触发点产生向外扩散的圆形涟漪效果，Material Design 风格的经典交互反馈。",
    category: "pointer",
    tags: ["ripple", "click", "material", "feedback", "interactive"],
    trigger: "on-click",
    difficulty: "intermediate",
    duration: "600ms",
    keywords: ["ripple", "click", "material design", "wave", "touch feedback", "button click"],
    playgroundMode: "js-driven",
    intensity: "low",
    input: "pointer-any",
  },
  {
    slug: "cursor-aura",
    name: "光晕指针",
    nameEn: "Cursor Aura",
    description: "在鼠标附近显示克制的柔和光晕，增强空间感但不替换系统光标。",
    category: "pointer",
    tags: ["cursor", "aura", "ambient", "pointer"],
    trigger: "continuous",
    difficulty: "intermediate",
    duration: "continuous",
    keywords: ["cursor aura", "custom cursor", "pointer follow", "ambient cursor"],
    playgroundMode: "js-driven",
    intensity: "low",
    input: "pointer-fine",
  },
  {
    slug: "cursor-trail",
    name: "指针轨迹",
    nameEn: "Cursor Trail",
    description: "多个小点延迟追随鼠标，形成短暂轨迹，适合演示页和创意页面。",
    category: "pointer",
    tags: ["cursor", "trail", "motion", "follow"],
    trigger: "continuous",
    difficulty: "advanced",
    duration: "continuous",
    keywords: ["cursor trail", "motion trail", "pointer dots", "lerp cursor"],
    playgroundMode: "js-driven",
    intensity: "high",
    input: "pointer-fine",
  },
  {
    slug: "proximity-reveal",
    name: "靠近显现",
    nameEn: "Proximity Reveal",
    description: "鼠标靠近时才显示辅助操作或信息，让密集界面保持安静。",
    category: "pointer",
    tags: ["proximity", "reveal", "hover", "utility"],
    trigger: "on-hover",
    difficulty: "intermediate",
    duration: "180ms",
    keywords: ["proximity reveal", "hover actions", "near cursor", "progressive disclosure"],
    playgroundMode: "js-driven",
    intensity: "low",
    input: "pointer-fine",
  },
  {
    slug: "text-repulsion",
    name: "文字排斥",
    nameEn: "Text Repulsion",
    description: "文字字符在鼠标靠近时轻微避让，适合标题和品牌字标的演示效果。",
    category: "pointer",
    tags: ["text", "repulsion", "pointer", "playful"],
    trigger: "continuous",
    difficulty: "advanced",
    duration: "continuous",
    keywords: ["text repulsion", "interactive typography", "cursor typography"],
    playgroundMode: "js-driven",
    intensity: "high",
    input: "pointer-fine",
  },
  {
    slug: "image-distortion",
    name: "图像扭曲",
    nameEn: "Image Distortion",
    description: "鼠标经过图像时产生局部液态位移，适合高表现力作品集和专题页。",
    category: "pointer",
    tags: ["image", "distortion", "pointer", "webgl"],
    trigger: "continuous",
    difficulty: "advanced",
    duration: "continuous",
    keywords: ["image distortion", "liquid hover", "displacement", "webgl hover"],
    playgroundMode: "js-driven",
    intensity: "high",
    input: "pointer-fine",
  },
  {
    slug: "parallax-layers",
    name: "鼠标视差层",
    nameEn: "Parallax Layers",
    description: "多层元素按不同强度响应鼠标位置，形成轻量空间深度。",
    category: "pointer",
    tags: ["parallax", "layers", "depth", "pointer"],
    trigger: "continuous",
    difficulty: "intermediate",
    duration: "continuous",
    keywords: ["mouse parallax", "parallax layers", "pointer depth", "hero parallax"],
    playgroundMode: "js-driven",
    intensity: "medium",
    input: "pointer-fine",
  },
  {
    slug: "drag-physics",
    name: "拖拽物理",
    nameEn: "Drag Physics",
    description: "拖拽对象带有惯性、吸附或回弹，提升画布类工具的手感。",
    category: "pointer",
    tags: ["drag", "physics", "inertia", "pointer"],
    trigger: "manual",
    difficulty: "advanced",
    duration: "continuous",
    keywords: ["drag physics", "inertia", "spring drag", "pointer capture"],
    playgroundMode: "js-driven",
    intensity: "medium",
    input: "pointer-any",
  },
  {
    slug: "context-cursor",
    name: "上下文光标",
    nameEn: "Context Cursor",
    description: "根据不同区域显示简短状态提示，例如拖拽、查看、复制或禁用。",
    category: "pointer",
    tags: ["cursor", "context", "status", "feedback"],
    trigger: "on-hover",
    difficulty: "intermediate",
    duration: "continuous",
    keywords: ["context cursor", "cursor label", "pointer status", "hover hint"],
    playgroundMode: "js-driven",
    intensity: "medium",
    input: "pointer-fine",
  },
  {
    slug: "counter-roll",
    name: "数字滚动",
    nameEn: "Counter Roll",
    description: "数字通过垂直滚动方式从 0 滚动至目标值，适合数据面板和统计展示。",
    category: "text",
    tags: ["counter", "number", "scroll", "data", "stats"],
    trigger: "on-scroll",
    difficulty: "intermediate",
    duration: "2s",
    keywords: ["counter", "number", "roll", "count up", "statistics", "dashboard"],
    playgroundMode: "scroll-driven",
  },
  {
    slug: "morph-shape",
    name: "形状变形",
    nameEn: "Morph Shape",
    description: "通过 border-radius 过渡实现有机的 blob 形状连续变形，适合装饰性背景元素。",
    category: "background",
    tags: ["morph", "blob", "organic", "background", "continuous"],
    trigger: "continuous",
    difficulty: "advanced",
    duration: "8s",
    keywords: ["morph", "blob", "shape", "organic", "border-radius", "ambient", "background"],
  },
  {
    slug: "fade-out-down",
    name: "淡出下滑",
    nameEn: "Fade Out Down",
    description: "元素向下滑动并逐渐消失，最常见的退场动画之一。",
    category: "exit",
    tags: ["fade", "slide", "exit", "unmount"],
    trigger: "manual",
    difficulty: "beginner",
    duration: "400ms",
    keywords: ["fade out", "slide down", "exit", "leave", "unmount animation"],
  },
  {
    slug: "zoom-in",
    name: "远景拉近",
    nameEn: "Zoom In",
    description: "元素从远处快速拉近至原始尺寸，带有强烈的纵深感和冲击力。",
    category: "entrance",
    tags: ["zoom", "scale", "entrance", "depth"],
    trigger: "on-mount",
    difficulty: "beginner",
    duration: "500ms",
    keywords: ["zoom", "scale up", "entrance", "depth", "camera"],
  },
  {
    slug: "marquee-scroll",
    name: "跑马灯滚动",
    nameEn: "Marquee Scroll",
    description: "文字或内容水平无限循环滚动，常用于公告栏、品牌展示和合作伙伴列表。",
    category: "text",
    tags: ["marquee", "scroll", "infinite", "loop", "horizontal"],
    trigger: "continuous",
    difficulty: "intermediate",
    duration: "20s",
    keywords: ["marquee", "scroll", "ticker", "infinite loop", "horizontal scroll", "brand logo"],
  },
  {
    slug: "shimmer",
    name: "微光扫过",
    nameEn: "Shimmer",
    description: "光线从左到右扫过元素表面，Apple 风格的加载占位符效果。",
    category: "loading",
    tags: ["shimmer", "shine", "loading", "skeleton", "apple"],
    trigger: "continuous",
    difficulty: "beginner",
    duration: "2s",
    keywords: ["shimmer", "shine", "skeleton", "loading", "placeholder", "apple"],
  },
  {
    slug: "pulse",
    name: "脉搏跳动",
    nameEn: "Pulse",
    description: "元素以心跳般的节奏缩放跳动，常用于提示用户注意或表示活跃状态。",
    category: "micro-interaction",
    tags: ["pulse", "heartbeat", "attention", "active", "notification"],
    trigger: "continuous",
    difficulty: "beginner",
    duration: "2s",
    keywords: ["pulse", "heartbeat", "beat", "attention", "notification", "active"],
  },
  {
    slug: "elastic-snap",
    name: "弹性回弹",
    nameEn: "Elastic Snap",
    description: "元素被拉伸后像橡皮筋一样弹性回弹到原位，充满物理质感的趣味交互。",
    category: "micro-interaction",
    tags: ["elastic", "spring", "rubber", "physics", "snap"],
    trigger: "on-click",
    difficulty: "intermediate",
    duration: "800ms",
    keywords: ["elastic", "spring", "rubber band", "snap", "physics", "stretch"],
  },
  {
    slug: "border-trace",
    name: "边框描边",
    nameEn: "Border Trace",
    description: "边框像被画笔描绘一样逐渐显现，从一角开始沿四边绘制完成。",
    category: "hover",
    tags: ["border", "draw", "trace", "outline", "svg"],
    trigger: "on-hover",
    difficulty: "advanced",
    duration: "600ms",
    keywords: ["border", "draw", "trace", "outline", "stroke", "pen"],
  },
  {
    slug: "glitch-text",
    name: "故障文字",
    nameEn: "Glitch Text",
    description: "文字以数字故障风格闪烁和偏移，带有赛博朋克美学的视觉冲击力。",
    category: "text",
    tags: ["glitch", "distortion", "cyberpunk", "effect", "text"],
    trigger: "continuous",
    difficulty: "advanced",
    duration: "3s",
    keywords: ["glitch", "distortion", "cyberpunk", "retro", "vhs", "noise"],
  },
  {
    slug: "scale-out",
    name: "缩放消失",
    nameEn: "Scale Out",
    description: "元素缩小并淡出，适合弹窗关闭、气泡消失等退场场景。",
    category: "exit",
    tags: ["scale", "zoom", "exit", "unmount"],
    trigger: "on-click",
    difficulty: "beginner",
    duration: "300ms",
    keywords: ["scale out", "zoom out", "exit", "shrink", "dismiss", "close"],
  },
  {
    slug: "slide-out-right",
    name: "右侧滑出",
    nameEn: "Slide Out Right",
    description: "元素向右侧滑出视口并消失，适合侧面板关闭、抽屉菜单收起等退场效果。",
    category: "exit",
    tags: ["slide", "exit", "horizontal", "panel"],
    trigger: "on-click",
    difficulty: "beginner",
    duration: "400ms",
    keywords: ["slide out", "right", "exit", "panel close", "drawer", "dismiss"],
  },
  {
    slug: "collapse",
    name: "折叠收起",
    nameEn: "Collapse",
    description: "元素高度从完整状态收缩至零并淡出，适合手风琴、FAQ 折叠面板等场景。",
    category: "exit",
    tags: ["collapse", "height", "exit", "accordion"],
    trigger: "on-click",
    difficulty: "intermediate",
    duration: "350ms",
    keywords: ["collapse", "accordion", "fold", "shrink height", "toggle", "expand"],
  },
  {
    slug: "crossfade",
    name: "交叉淡化",
    nameEn: "Crossfade",
    description: "两个元素交叉切换：一个淡出的同时另一个淡入，实现平滑的内容过渡。",
    category: "transition",
    tags: ["fade", "crossfade", "transition", "swap"],
    trigger: "manual",
    difficulty: "intermediate",
    duration: "500ms",
    keywords: ["crossfade", "dissolve", "swap", "transition", "toggle", "tab switch"],
  },
  {
    slug: "slide-swap",
    name: "滑动切换",
    nameEn: "Slide Swap",
    description: "新旧内容以水平滑动方式交替切换，旧内容滑出左侧的同时新内容从右侧滑入。",
    category: "transition",
    tags: ["slide", "swap", "transition", "horizontal"],
    trigger: "manual",
    difficulty: "intermediate",
    duration: "400ms",
    keywords: ["slide swap", "horizontal transition", "tab slide", "page transition", "carousel"],
  },
  {
    slug: "morph-transition",
    name: "形态过渡",
    nameEn: "Morph Transition",
    description: "元素在两种形态之间平滑过渡，包括尺寸、圆角、颜色等属性的同步变化。",
    category: "transition",
    tags: ["morph", "transition", "shape", "state"],
    trigger: "continuous",
    difficulty: "advanced",
    duration: "600ms",
    keywords: ["morph", "shape shift", "state transition", "layout animation", "FLIP"],
  },
  {
    slug: "text-reveal",
    name: "文字揭示",
    nameEn: "Text Reveal",
    description: "文字通过遮罩从下方逐行揭示显现，常用于英雄区标题和关键文案的戏剧性入场。",
    category: "text",
    tags: ["text", "reveal", "mask", "clip", "scroll"],
    trigger: "on-scroll",
    difficulty: "intermediate",
    duration: "800ms",
    keywords: ["text reveal", "mask", "clip path", "hero text", "headline animation", "scroll text"],
  },
  {
    slug: "underline-draw",
    name: "下划线绘制",
    nameEn: "Underline Draw",
    description: "鼠标悬停时下划线从左到右绘制展开，离开时反向收回，经典的导航链接交互效果。",
    category: "hover",
    tags: ["hover", "underline", "draw", "link", "navigation"],
    trigger: "on-hover",
    difficulty: "beginner",
    duration: "300ms",
    keywords: ["underline", "draw", "hover link", "navigation", "text decoration", "line animation"],
  },
  {
    slug: "progress-bar",
    name: "进度条加载",
    nameEn: "Progress Bar",
    description: "进度条从左到右填充并带有光泽扫过效果，适合加载状态和进度指示场景。",
    category: "loading",
    tags: ["loading", "progress", "bar", "shimmer"],
    trigger: "continuous",
    difficulty: "beginner",
    duration: "2s",
    keywords: ["progress bar", "loading bar", "shimmer", "fill", "indicator", "status"],
  },
  {
    slug: "elastic-scale",
    name: "弹簧缩放",
    nameEn: "Elastic Scale",
    description: "元素以弹簧物理效果入场，多次过冲和回弹后稳定，比 bounce-in 更夸张的弹性感。",
    category: "entrance",
    tags: ["elastic", "spring", "scale", "entrance", "physics"],
    trigger: "on-mount",
    difficulty: "intermediate",
    duration: "800ms",
    keywords: ["elastic", "spring", "bounce", "overshoot", "physics", "entrance", "playful"],
  },
  {
    slug: "pulse-ring",
    name: "脉冲光环",
    nameEn: "Pulse Ring",
    description: "从元素中心向外扩散的脉冲圆环效果，适合状态指示器、在线标志和注意力引导。",
    category: "micro-interaction",
    tags: ["pulse", "ring", "status", "attention", "continuous"],
    trigger: "continuous",
    difficulty: "beginner",
    duration: "2s",
    keywords: ["pulse", "ring", "beacon", "status indicator", "online", "notification", "ping"],
  },
  {
    slug: "text-scramble",
    name: "文字解密",
    nameEn: "Text Scramble",
    description: "文字以随机字符快速滚动后逐字解密为最终内容，常见于黑客终端和科技品牌网站。",
    category: "text",
    tags: ["text", "scramble", "decode", "hacker", "sequential"],
    trigger: "on-mount",
    difficulty: "intermediate",
    duration: "1.5s",
    keywords: ["scramble", "decode", "cipher", "hacker", "terminal", "reveal text"],
  },
  {
    slug: "tilt-3d",
    name: "3D 透视倾斜",
    nameEn: "3D Tilt",
    description: "鼠标在卡片上移动时，卡片随鼠标位置产生 3D 透视倾斜效果，营造沉浸式的空间深度感。",
    category: "pointer",
    tags: ["3d", "perspective", "tilt", "hover", "mouse-tracking"],
    trigger: "on-hover",
    difficulty: "intermediate",
    duration: "continuous",
    keywords: ["3d tilt", "perspective", "mouse tracking", "card hover", "parallax card"],
    playgroundMode: "js-driven",
    intensity: "medium",
    input: "pointer-fine",
  },
  {
    slug: "confetti-burst",
    name: "彩纸爆炸",
    nameEn: "Confetti Burst",
    description: "点击时从触发点向四周射出彩色纸片粒子，适合成功状态、庆祝和游戏化场景的视觉反馈。",
    category: "micro-interaction",
    tags: ["confetti", "particle", "celebration", "click", "success"],
    trigger: "on-click",
    difficulty: "advanced",
    duration: "1.2s",
    keywords: ["confetti", "celebration", "particle", "burst", "success", "reward"],
    playgroundMode: "js-driven",
  },
  {
    slug: "scroll-page-turn",
    name: "滚动翻页",
    nameEn: "Scroll Page Turn",
    description: "滚动驱动的 3D 翻页效果，页面像书页一样沿 Y 轴翻转剥离，露出下一页内容。",
    category: "scroll",
    tags: ["scroll", "3d", "page-turn", "perspective", "sticky", "apple"],
    trigger: "on-scroll",
    difficulty: "advanced",
    duration: "continuous",
    keywords: ["page turn", "book flip", "scroll animation", "3D", "perspective", "apple", "sticky scroll", "cinematic"],
    playgroundMode: "scroll-driven",
  },
  {
    slug: "scroll-peel-away",
    name: "滚动剥离",
    nameEn: "Scroll Peel Away",
    description: "滚动驱动的页面剥离效果，当前页面像贴纸一样从右上角卷起剥离，露出下一层内容。",
    category: "scroll",
    tags: ["scroll", "3d", "peel", "curl", "paper", "sticky", "apple"],
    trigger: "on-scroll",
    difficulty: "advanced",
    duration: "continuous",
    keywords: ["peel", "curl", "paper", "sticker", "scroll animation", "3D", "apple", "page transition"],
    playgroundMode: "scroll-driven",
  },
];

export function getAllAnimationsMeta(): AnimationMeta[] {
  return animationsMeta;
}

export function getAnimationMetaBySlug(slug: string): AnimationMeta | undefined {
  return animationsMeta.find((a) => a.slug === slug);
}
