// Blog Layout Archetypes

import type { LayoutArchetype } from "./types";

export const blogArchetypes: LayoutArchetype[] = [
  {
    id: "blog-classic",
    name: "Classic Blog",
    nameZh: "经典博客",
    category: "blog",
    description: "Traditional blog layout with featured post and post grid.",
    descriptionZh: "经典博客布局，精选文章 + 文章网格",
    sections: [
      {
        id: "header",
        name: "Header",
        nameZh: "顶栏",
        required: true,
        order: 1,
        layout: {
          type: "contained",
          maxWidth: "6xl",
          padding: "sm",
        },
        components: ["nav", "button"],
      },
      {
        id: "featured",
        name: "Featured Post",
        nameZh: "精选文章",
        required: false,
        order: 2,
        layout: {
          type: "contained",
          maxWidth: "6xl",
          padding: "lg",
        },
        components: ["card", "heading", "badge"],
      },
      {
        id: "posts",
        name: "Post Grid",
        nameZh: "文章列表",
        required: true,
        order: 3,
        layout: {
          type: "grid",
          maxWidth: "6xl",
          columns: { mobile: 1, tablet: 2, desktop: 3 },
          padding: "lg",
          gap: "md",
        },
        components: ["card"],
      },
      {
        id: "pagination",
        name: "Pagination",
        nameZh: "分页",
        required: true,
        order: 4,
        layout: {
          type: "contained",
          maxWidth: "6xl",
          padding: "md",
          horizontalAlign: "center",
        },
        components: ["button"],
      },
      {
        id: "footer",
        name: "Footer",
        nameZh: "页脚",
        required: true,
        order: 5,
        layout: { type: "contained", maxWidth: "6xl", padding: "md" },
        components: ["nav"],
      },
    ],
    responsive: {
      mobile: "Single column posts. Featured post card simplified.",
      tablet: "2-column post grid.",
      desktop: "3-column post grid. Large featured post.",
    },
    tags: ["content", "articles", "news"],
  },

  {
    id: "blog-magazine",
    name: "Magazine Style",
    nameZh: "杂志风格",
    category: "blog",
    description: "Magazine-style layout with varied card sizes and sidebar.",
    descriptionZh: "杂志风格布局，卡片大小不一 + 侧边栏",
    sections: [
      {
        id: "header",
        name: "Header",
        nameZh: "顶栏",
        required: true,
        order: 1,
        layout: {
          type: "contained",
          maxWidth: "7xl",
          padding: "sm",
        },
        components: ["nav", "input"],
      },
      {
        id: "main-with-sidebar",
        name: "Main Content",
        nameZh: "主内容",
        required: true,
        order: 2,
        layout: {
          type: "sidebar",
          maxWidth: "7xl",
          padding: "lg",
          gap: "lg",
        },
        components: ["card", "heading"],
      },
      {
        id: "footer",
        name: "Footer",
        nameZh: "页脚",
        required: true,
        order: 3,
        layout: { type: "contained", maxWidth: "7xl", padding: "md" },
        components: ["nav"],
      },
    ],
    responsive: {
      mobile: "Sidebar moves below main content. Single column.",
      tablet: "2-column main grid. Sidebar below.",
      desktop: "Main content + sidebar layout. Magazine grid.",
    },
    tags: ["editorial", "magazine", "news"],
  },

  {
    id: "blog-minimal",
    name: "Minimal Blog",
    nameZh: "极简博客",
    category: "blog",
    description: "Clean, text-focused blog layout with no images. Perfect for writing.",
    descriptionZh: "纯文字列表，无图片，专注阅读体验",
    sections: [
      {
        id: "header",
        name: "Header",
        nameZh: "顶栏",
        required: true,
        order: 1,
        layout: {
          type: "contained",
          maxWidth: "2xl",
          padding: "md",
          horizontalAlign: "center",
        },
        components: ["heading", "nav"],
        description: "Site name and minimal navigation",
      },
      {
        id: "posts",
        name: "Post List",
        nameZh: "文章列表",
        required: true,
        order: 2,
        layout: {
          type: "stack",
          maxWidth: "2xl",
          padding: "lg",
          gap: "lg",
        },
        components: ["heading", "paragraph"],
        description: "Simple list of posts with title, date, and excerpt",
        slots: [
          { id: "posts", name: "Post Items", type: "list", required: true },
        ],
      },
      {
        id: "pagination",
        name: "Pagination",
        nameZh: "分页",
        required: true,
        order: 3,
        layout: {
          type: "contained",
          maxWidth: "2xl",
          padding: "md",
          horizontalAlign: "center",
        },
        components: ["button"],
      },
      {
        id: "footer",
        name: "Footer",
        nameZh: "页脚",
        required: true,
        order: 4,
        layout: {
          type: "contained",
          maxWidth: "2xl",
          padding: "md",
          horizontalAlign: "center",
        },
        components: ["nav", "paragraph"],
        description: "Minimal footer with social links",
      },
    ],
    responsive: {
      mobile: "Narrow container. Generous line height for readability.",
      tablet: "Wider container. Same minimal layout.",
      desktop: "Max-width 2xl for optimal reading. Clean typography.",
    },
    tags: ["minimal", "writing", "typography", "personal"],
  },

  {
    id: "blog-grid",
    name: "Grid Blog",
    nameZh: "网格博客",
    category: "blog",
    description: "Pinterest-style masonry grid layout for visual blogs.",
    descriptionZh: "瀑布流网格布局，适合图片丰富的博客",
    sections: [
      {
        id: "header",
        name: "Header",
        nameZh: "顶栏",
        required: true,
        order: 1,
        layout: {
          type: "contained",
          maxWidth: "7xl",
          padding: "sm",
        },
        components: ["nav", "input", "button"],
        description: "Navigation with search and category filters",
      },
      {
        id: "filters",
        name: "Category Filters",
        nameZh: "分类筛选",
        required: false,
        order: 2,
        layout: {
          type: "contained",
          maxWidth: "7xl",
          padding: "sm",
          horizontalAlign: "center",
        },
        components: ["button", "badge"],
        description: "Category tags or filter buttons",
      },
      {
        id: "posts",
        name: "Post Grid",
        nameZh: "文章网格",
        required: true,
        order: 3,
        layout: {
          type: "grid",
          maxWidth: "7xl",
          columns: { mobile: 1, tablet: 2, desktop: 4 },
          padding: "lg",
          gap: "md",
        },
        components: ["card"],
        description: "Masonry-style grid of post cards with images",
      },
      {
        id: "load-more",
        name: "Load More",
        nameZh: "加载更多",
        required: true,
        order: 4,
        layout: {
          type: "contained",
          maxWidth: "7xl",
          padding: "lg",
          horizontalAlign: "center",
        },
        components: ["button"],
        description: "Infinite scroll or load more button",
      },
      {
        id: "footer",
        name: "Footer",
        nameZh: "页脚",
        required: true,
        order: 5,
        layout: { type: "contained", maxWidth: "7xl", padding: "md" },
        components: ["nav"],
      },
    ],
    responsive: {
      mobile: "Single column cards. Full-width images.",
      tablet: "2-column grid. Category filters scroll horizontally.",
      desktop: "4-column masonry grid. Hover effects on cards.",
    },
    tags: ["visual", "pinterest", "gallery", "images"],
  },
];
