// E-commerce Layout Archetypes

import type { LayoutArchetype } from "./types";

export const ecommerceArchetypes: LayoutArchetype[] = [
  {
    id: "ecommerce-product-grid",
    name: "Product Grid",
    nameZh: "商品网格",
    category: "ecommerce",
    description: "Classic e-commerce layout with filter sidebar and product grid.",
    descriptionZh: "筛选侧边栏 + 商品网格，经典电商布局",
    sections: [
      {
        id: "header",
        name: "Header",
        nameZh: "顶栏",
        required: true,
        order: 1,
        layout: {
          type: "full-width",
          padding: "sm",
        },
        components: ["nav", "input", "button", "badge"],
        description: "Navigation, search, cart, and user menu",
      },
      {
        id: "breadcrumb",
        name: "Breadcrumb",
        nameZh: "面包屑",
        required: false,
        order: 2,
        layout: {
          type: "contained",
          maxWidth: "7xl",
          padding: "sm",
        },
        components: ["nav"],
        description: "Category breadcrumb navigation",
      },
      {
        id: "category-header",
        name: "Category Header",
        nameZh: "分类标题",
        required: true,
        order: 3,
        layout: {
          type: "contained",
          maxWidth: "7xl",
          padding: "md",
        },
        components: ["heading", "paragraph"],
        description: "Category name, description, and product count",
      },
      {
        id: "filters-and-products",
        name: "Filters & Products",
        nameZh: "筛选与商品",
        required: true,
        order: 4,
        layout: {
          type: "sidebar",
          maxWidth: "7xl",
          padding: "md",
          gap: "lg",
        },
        components: ["card", "button", "input"],
        description: "Filter sidebar with product grid",
        slots: [
          { id: "filters", name: "Filter Panel", type: "component", required: true },
          { id: "products", name: "Product Grid", type: "list", required: true },
        ],
      },
      {
        id: "pagination",
        name: "Pagination",
        nameZh: "分页",
        required: true,
        order: 5,
        layout: {
          type: "contained",
          maxWidth: "7xl",
          padding: "md",
          horizontalAlign: "center",
        },
        components: ["button"],
      },
      {
        id: "footer",
        name: "Footer",
        nameZh: "页脚",
        required: true,
        order: 6,
        layout: { type: "contained", maxWidth: "7xl", padding: "lg" },
        components: ["nav"],
      },
    ],
    responsive: {
      mobile: "Filters in modal/drawer. 2-column product grid.",
      tablet: "Collapsible filter sidebar. 3-column grid.",
      desktop: "280px filter sidebar. 4-column product grid.",
    },
    tags: ["shop", "catalog", "products", "filters"],
  },

  {
    id: "ecommerce-product-detail",
    name: "Product Detail",
    nameZh: "商品详情",
    category: "ecommerce",
    description: "Product detail page with image gallery, info, and reviews.",
    descriptionZh: "图片画廊 + 商品信息 + 评价，商品详情页",
    sections: [
      {
        id: "header",
        name: "Header",
        nameZh: "顶栏",
        required: true,
        order: 1,
        layout: {
          type: "full-width",
          padding: "sm",
        },
        components: ["nav", "input", "button", "badge"],
      },
      {
        id: "breadcrumb",
        name: "Breadcrumb",
        nameZh: "面包屑",
        required: false,
        order: 2,
        layout: {
          type: "contained",
          maxWidth: "7xl",
          padding: "sm",
        },
        components: ["nav"],
      },
      {
        id: "product-main",
        name: "Product Info",
        nameZh: "商品信息",
        required: true,
        order: 3,
        layout: {
          type: "split",
          maxWidth: "7xl",
          ratio: "1:1",
          padding: "lg",
          gap: "lg",
          verticalAlign: "top",
        },
        components: ["card", "heading", "paragraph", "button", "badge"],
        description: "Image gallery on left, product details on right",
        slots: [
          { id: "gallery", name: "Image Gallery", type: "component", required: true },
          { id: "title", name: "Product Title", type: "heading", required: true },
          { id: "price", name: "Price", type: "text", required: true },
          { id: "description", name: "Description", type: "paragraph", required: true },
          { id: "options", name: "Product Options", type: "component", required: false },
          { id: "addToCart", name: "Add to Cart", type: "component", required: true },
        ],
      },
      {
        id: "product-details",
        name: "Product Details",
        nameZh: "详细信息",
        required: true,
        order: 4,
        layout: {
          type: "contained",
          maxWidth: "7xl",
          padding: "lg",
        },
        components: ["card", "heading"],
        description: "Tabs for description, specs, shipping info",
      },
      {
        id: "reviews",
        name: "Reviews",
        nameZh: "评价",
        required: true,
        order: 5,
        layout: {
          type: "contained",
          maxWidth: "7xl",
          padding: "lg",
        },
        components: ["card", "heading", "paragraph", "button"],
        description: "Customer reviews and ratings",
      },
      {
        id: "related-products",
        name: "Related Products",
        nameZh: "相关商品",
        required: false,
        order: 6,
        layout: {
          type: "grid",
          maxWidth: "7xl",
          columns: { mobile: 2, tablet: 3, desktop: 4 },
          padding: "lg",
          gap: "md",
        },
        components: ["card"],
        description: "Related or recommended products",
      },
      {
        id: "footer",
        name: "Footer",
        nameZh: "页脚",
        required: true,
        order: 7,
        layout: { type: "contained", maxWidth: "7xl", padding: "lg" },
        components: ["nav"],
      },
    ],
    responsive: {
      mobile: "Gallery stacks above info. Single column layout.",
      tablet: "Side-by-side gallery and info. 3-column related.",
      desktop: "Large gallery with thumbnails. Full split layout.",
    },
    tags: ["product", "detail", "gallery", "reviews"],
  },

  {
    id: "ecommerce-checkout",
    name: "Checkout Flow",
    nameZh: "结账流程",
    category: "ecommerce",
    description: "Multi-step checkout with order summary sidebar.",
    descriptionZh: "多步骤结账表单 + 订单摘要侧边栏",
    sections: [
      {
        id: "header",
        name: "Checkout Header",
        nameZh: "结账顶栏",
        required: true,
        order: 1,
        layout: {
          type: "contained",
          maxWidth: "6xl",
          padding: "sm",
        },
        components: ["heading", "badge"],
        description: "Simplified header with logo and security badge",
      },
      {
        id: "progress",
        name: "Progress Steps",
        nameZh: "进度步骤",
        required: true,
        order: 2,
        layout: {
          type: "contained",
          maxWidth: "4xl",
          padding: "md",
          horizontalAlign: "center",
        },
        components: ["badge"],
        description: "Step indicator (Cart > Shipping > Payment > Confirm)",
      },
      {
        id: "checkout-main",
        name: "Checkout Form",
        nameZh: "结账表单",
        required: true,
        order: 3,
        layout: {
          type: "sidebar",
          maxWidth: "6xl",
          padding: "lg",
          gap: "lg",
        },
        components: ["card", "input", "button"],
        description: "Form area with order summary sidebar",
        slots: [
          { id: "form", name: "Checkout Form", type: "component", required: true },
          { id: "orderSummary", name: "Order Summary", type: "component", required: true },
        ],
      },
      {
        id: "trust-signals",
        name: "Trust Signals",
        nameZh: "信任标识",
        required: false,
        order: 4,
        layout: {
          type: "contained",
          maxWidth: "4xl",
          padding: "md",
          horizontalAlign: "center",
        },
        components: ["badge"],
        description: "Security badges, payment icons, guarantees",
      },
      {
        id: "footer",
        name: "Footer",
        nameZh: "页脚",
        required: true,
        order: 5,
        layout: {
          type: "contained",
          maxWidth: "6xl",
          padding: "sm",
          horizontalAlign: "center",
        },
        components: ["nav"],
        description: "Minimal footer with support links",
      },
    ],
    responsive: {
      mobile: "Single column. Order summary collapsible at top.",
      tablet: "Side-by-side form and summary.",
      desktop: "Form takes 2/3, order summary sticky sidebar.",
    },
    tags: ["checkout", "payment", "cart", "conversion"],
  },
];
