// Form Layout Archetypes

import type { LayoutArchetype } from "./types";

export const formArchetypes: LayoutArchetype[] = [
  {
    id: "form-multi-step",
    name: "Multi-Step Form",
    nameZh: "多步骤表单",
    category: "form",
    description: "Wizard-style form with progress indicator and step-by-step input.",
    descriptionZh: "进度条 + 分步表单，适合复杂数据收集",
    sections: [
      {
        id: "header",
        name: "Form Header",
        nameZh: "表单顶栏",
        required: true,
        order: 1,
        layout: {
          type: "contained",
          maxWidth: "4xl",
          padding: "md",
          horizontalAlign: "center",
        },
        components: ["heading", "paragraph"],
        description: "Form title and description",
      },
      {
        id: "progress",
        name: "Progress Indicator",
        nameZh: "进度指示",
        required: true,
        order: 2,
        layout: {
          type: "contained",
          maxWidth: "2xl",
          padding: "md",
          horizontalAlign: "center",
        },
        components: ["badge"],
        description: "Step indicators or progress bar",
        slots: [
          { id: "steps", name: "Step Indicators", type: "component", required: true },
        ],
      },
      {
        id: "form-content",
        name: "Form Content",
        nameZh: "表单内容",
        required: true,
        order: 3,
        layout: {
          type: "contained",
          maxWidth: "2xl",
          padding: "lg",
        },
        components: ["card", "input", "button"],
        description: "Current step form fields",
        slots: [
          { id: "fields", name: "Form Fields", type: "component", required: true },
        ],
      },
      {
        id: "navigation",
        name: "Form Navigation",
        nameZh: "表单导航",
        required: true,
        order: 4,
        layout: {
          type: "contained",
          maxWidth: "2xl",
          padding: "md",
        },
        components: ["button"],
        description: "Back and Next/Submit buttons",
      },
      {
        id: "help",
        name: "Help Section",
        nameZh: "帮助区域",
        required: false,
        order: 5,
        layout: {
          type: "contained",
          maxWidth: "2xl",
          padding: "sm",
          horizontalAlign: "center",
        },
        components: ["paragraph", "button"],
        description: "FAQ or support links",
      },
    ],
    responsive: {
      mobile: "Full-width form. Progress as dots. Stacked buttons.",
      tablet: "Wider container. Progress bar visible.",
      desktop: "Centered max-width container. Inline navigation buttons.",
    },
    tags: ["wizard", "onboarding", "registration", "survey"],
  },

  {
    id: "form-settings",
    name: "Settings Page",
    nameZh: "设置页面",
    category: "form",
    description: "Settings page with sidebar navigation and form sections.",
    descriptionZh: "侧边导航 + 表单区域，适合账户设置",
    sections: [
      {
        id: "header",
        name: "Page Header",
        nameZh: "页面标题",
        required: true,
        order: 1,
        layout: {
          type: "contained",
          maxWidth: "6xl",
          padding: "md",
        },
        components: ["heading", "paragraph"],
        description: "Settings page title",
      },
      {
        id: "settings-layout",
        name: "Settings Layout",
        nameZh: "设置布局",
        required: true,
        order: 2,
        layout: {
          type: "sidebar",
          maxWidth: "6xl",
          padding: "lg",
          gap: "lg",
        },
        components: ["nav", "card", "input", "button"],
        description: "Navigation sidebar with settings forms",
        slots: [
          { id: "navigation", name: "Settings Nav", type: "component", required: true },
          { id: "content", name: "Settings Content", type: "component", required: true },
        ],
      },
      {
        id: "section-profile",
        name: "Profile Section",
        nameZh: "个人资料",
        required: true,
        order: 3,
        layout: {
          type: "stack",
          padding: "md",
          gap: "md",
          background: "secondary",
        },
        components: ["heading", "input", "button", "card"],
        description: "Profile settings form",
      },
      {
        id: "section-security",
        name: "Security Section",
        nameZh: "安全设置",
        required: true,
        order: 4,
        layout: {
          type: "stack",
          padding: "md",
          gap: "md",
        },
        components: ["heading", "input", "button", "card"],
        description: "Password and security settings",
      },
      {
        id: "section-notifications",
        name: "Notifications Section",
        nameZh: "通知设置",
        required: false,
        order: 5,
        layout: {
          type: "stack",
          padding: "md",
          gap: "md",
        },
        components: ["heading", "card", "button"],
        description: "Notification preferences",
      },
      {
        id: "danger-zone",
        name: "Danger Zone",
        nameZh: "危险操作",
        required: false,
        order: 6,
        layout: {
          type: "contained",
          padding: "md",
          background: "accent",
        },
        components: ["heading", "paragraph", "button"],
        description: "Account deletion and destructive actions",
      },
    ],
    responsive: {
      mobile: "Navigation as tabs at top. Single column forms.",
      tablet: "Sidebar navigation visible. Forms full-width.",
      desktop: "240px sidebar. Form sections with max-width.",
    },
    tags: ["settings", "account", "preferences", "admin"],
  },
];
