// Landing Page Layout Archetypes

import type { LayoutArchetype } from "./types";

export const landingArchetypes: LayoutArchetype[] = [
  {
    id: "landing-hero-centered",
    name: "Centered Hero",
    nameZh: "居中 Hero",
    category: "landing",
    description: "Centered headline, subtitle, and CTA. Clean and focused.",
    descriptionZh: "标题、副标题、CTA 居中显示，适合简洁的产品介绍",
    sections: [
      {
        id: "hero",
        name: "Hero",
        nameZh: "Hero 区块",
        required: true,
        order: 1,
        layout: {
          type: "contained",
          maxWidth: "4xl",
          minHeight: "80vh",
          padding: "lg",
          verticalAlign: "center",
          horizontalAlign: "center",
        },
        components: ["heading", "paragraph", "button", "badge"],
        description: "Main headline with subtitle and primary CTA",
        slots: [
          { id: "badge", name: "Badge", type: "text", required: false },
          { id: "headline", name: "Headline", type: "heading", required: true },
          { id: "subtitle", name: "Subtitle", type: "paragraph", required: true },
          { id: "cta", name: "CTA Buttons", type: "component", required: true },
        ],
      },
      {
        id: "features",
        name: "Features",
        nameZh: "特性区块",
        required: true,
        order: 2,
        layout: {
          type: "grid",
          maxWidth: "6xl",
          columns: { mobile: 1, tablet: 2, desktop: 3 },
          padding: "lg",
          gap: "md",
        },
        components: ["card"],
        description: "Feature cards showcasing key benefits",
        slots: [
          { id: "sectionTitle", name: "Section Title", type: "heading", required: false },
          { id: "cards", name: "Feature Cards", type: "list", required: true },
        ],
      },
      {
        id: "social-proof",
        name: "Social Proof",
        nameZh: "社会认证",
        required: false,
        order: 3,
        layout: {
          type: "contained",
          maxWidth: "6xl",
          padding: "lg",
          horizontalAlign: "center",
          background: "secondary",
        },
        components: ["card", "heading"],
        description: "Testimonials, logos, or trust signals",
      },
      {
        id: "cta-section",
        name: "CTA Section",
        nameZh: "行动召唤",
        required: true,
        order: 4,
        layout: {
          type: "contained",
          maxWidth: "2xl",
          padding: "xl",
          horizontalAlign: "center",
        },
        components: ["heading", "button", "input"],
        description: "Final conversion-focused call to action",
      },
      {
        id: "footer",
        name: "Footer",
        nameZh: "页脚",
        required: true,
        order: 5,
        layout: {
          type: "contained",
          maxWidth: "6xl",
          padding: "md",
        },
        components: ["nav"],
        description: "Footer with links and copyright",
      },
    ],
    responsive: {
      mobile: "Single column stack. Hero min-height 60vh. Features in 1 column.",
      tablet: "Features in 2-column grid. Increased padding.",
      desktop: "Features in 3-column grid. Hero 80vh. Max-width containers.",
    },
    tags: ["product", "saas", "startup"],
  },

  {
    id: "landing-hero-split",
    name: "Split Hero",
    nameZh: "左右分屏 Hero",
    category: "landing",
    description: "Text on left, image/visual on right. Great for product showcases.",
    descriptionZh: "左侧文字 + 右侧图片/插画，适合展示产品截图",
    sections: [
      {
        id: "hero",
        name: "Hero",
        nameZh: "Hero 区块",
        required: true,
        order: 1,
        layout: {
          type: "split",
          ratio: "1:1",
          maxWidth: "7xl",
          minHeight: "80vh",
          padding: "lg",
          verticalAlign: "center",
          gap: "lg",
        },
        components: ["heading", "paragraph", "button", "badge"],
        description: "Split layout with text content and hero image",
        slots: [
          { id: "headline", name: "Headline", type: "heading", required: true },
          { id: "subtitle", name: "Subtitle", type: "paragraph", required: true },
          { id: "cta", name: "CTA Buttons", type: "component", required: true },
          { id: "heroImage", name: "Hero Image", type: "image", required: true },
        ],
      },
      {
        id: "logos",
        name: "Logo Bar",
        nameZh: "品牌栏",
        required: false,
        order: 2,
        layout: {
          type: "contained",
          maxWidth: "6xl",
          padding: "sm",
          horizontalAlign: "center",
        },
        components: [],
        description: "Trusted-by logo bar",
      },
      {
        id: "features",
        name: "Features",
        nameZh: "特性区块",
        required: true,
        order: 3,
        layout: {
          type: "grid",
          maxWidth: "6xl",
          columns: { mobile: 1, tablet: 2, desktop: 3 },
          padding: "lg",
          gap: "md",
        },
        components: ["card"],
      },
      {
        id: "cta-section",
        name: "CTA Section",
        nameZh: "行动召唤",
        required: true,
        order: 4,
        layout: {
          type: "contained",
          maxWidth: "4xl",
          padding: "xl",
          horizontalAlign: "center",
        },
        components: ["heading", "button"],
      },
      {
        id: "footer",
        name: "Footer",
        nameZh: "页脚",
        required: true,
        order: 5,
        layout: { type: "contained", maxWidth: "6xl", padding: "md" },
        components: ["nav"],
      },
    ],
    responsive: {
      mobile: "Image stacks above text. Single column features.",
      tablet: "Split layout maintained. Features 2 columns.",
      desktop: "Full split 1:1 with max-width constraint. Features 3 columns.",
    },
    tags: ["product", "showcase", "app"],
  },

  {
    id: "landing-hero-fullscreen",
    name: "Fullscreen Hero",
    nameZh: "全屏 Hero",
    category: "landing",
    description: "Full viewport hero with background image or color. High impact.",
    descriptionZh: "全屏背景的 Hero 区块，视觉冲击力强",
    sections: [
      {
        id: "hero",
        name: "Hero",
        nameZh: "Hero 区块",
        required: true,
        order: 1,
        layout: {
          type: "full-width",
          minHeight: "100vh",
          padding: "lg",
          verticalAlign: "center",
          horizontalAlign: "center",
          background: "accent",
        },
        components: ["heading", "paragraph", "button"],
        slots: [
          { id: "headline", name: "Headline", type: "heading", required: true },
          { id: "subtitle", name: "Subtitle", type: "paragraph", required: false },
          { id: "cta", name: "CTA", type: "component", required: true },
        ],
      },
      {
        id: "about",
        name: "About",
        nameZh: "介绍",
        required: true,
        order: 2,
        layout: {
          type: "split",
          maxWidth: "6xl",
          ratio: "1:1",
          padding: "xl",
          gap: "lg",
        },
        components: ["heading", "paragraph"],
      },
      {
        id: "features",
        name: "Features",
        nameZh: "特性",
        required: true,
        order: 3,
        layout: {
          type: "grid",
          maxWidth: "6xl",
          columns: { mobile: 1, tablet: 2, desktop: 4 },
          padding: "lg",
          gap: "md",
        },
        components: ["card"],
      },
      {
        id: "footer",
        name: "Footer",
        nameZh: "页脚",
        required: true,
        order: 4,
        layout: { type: "contained", maxWidth: "6xl", padding: "md" },
        components: ["nav"],
      },
    ],
    responsive: {
      mobile: "Hero still full viewport. Features single column.",
      tablet: "Features 2 columns. About section stacks.",
      desktop: "Full 100vh hero. Features 4-column grid. Split about section.",
    },
    tags: ["creative", "bold", "portfolio"],
  },

  {
    id: "landing-video-hero",
    name: "Video Background Hero",
    nameZh: "视频背景 Hero",
    category: "landing",
    description: "Full-screen video background with overlay text. High impact for product demos.",
    descriptionZh: "全屏视频背景，适合产品演示和品牌展示",
    sections: [
      {
        id: "hero",
        name: "Video Hero",
        nameZh: "视频 Hero",
        required: true,
        order: 1,
        layout: {
          type: "full-width",
          minHeight: "100vh",
          padding: "lg",
          verticalAlign: "center",
          horizontalAlign: "center",
        },
        components: ["heading", "paragraph", "button"],
        slots: [
          { id: "video", name: "Background Video", type: "component", required: true },
          { id: "headline", name: "Headline", type: "heading", required: true },
          { id: "subtitle", name: "Subtitle", type: "paragraph", required: false },
          { id: "cta", name: "CTA Buttons", type: "component", required: true },
        ],
      },
      {
        id: "features",
        name: "Features",
        nameZh: "特性展示",
        required: true,
        order: 2,
        layout: {
          type: "grid",
          maxWidth: "6xl",
          columns: { mobile: 1, tablet: 2, desktop: 3 },
          padding: "xl",
          gap: "lg",
        },
        components: ["card"],
      },
      {
        id: "demo",
        name: "Product Demo",
        nameZh: "产品演示",
        required: false,
        order: 3,
        layout: {
          type: "contained",
          maxWidth: "4xl",
          padding: "xl",
          horizontalAlign: "center",
        },
        components: ["heading", "paragraph"],
        description: "Embedded video or interactive demo",
      },
      {
        id: "cta-section",
        name: "CTA Section",
        nameZh: "行动召唤",
        required: true,
        order: 4,
        layout: {
          type: "contained",
          maxWidth: "2xl",
          padding: "xl",
          horizontalAlign: "center",
          background: "accent",
        },
        components: ["heading", "button"],
      },
      {
        id: "footer",
        name: "Footer",
        nameZh: "页脚",
        required: true,
        order: 5,
        layout: { type: "contained", maxWidth: "6xl", padding: "md" },
        components: ["nav"],
      },
    ],
    responsive: {
      mobile: "Video replaced with static image on slow connections. Single column features.",
      tablet: "Video plays. Features 2-column grid.",
      desktop: "Full 100vh video hero. Features 3-column. Large demo section.",
    },
    tags: ["product", "demo", "immersive", "brand"],
  },

  {
    id: "landing-saas-pricing",
    name: "SaaS Pricing Page",
    nameZh: "SaaS 定价页",
    category: "landing",
    description: "Complete SaaS pricing page with hero, pricing tiers, FAQ, and CTA.",
    descriptionZh: "SaaS 产品定价页，包含定价表、FAQ 和转化区块",
    sections: [
      {
        id: "hero",
        name: "Pricing Hero",
        nameZh: "定价 Hero",
        required: true,
        order: 1,
        layout: {
          type: "contained",
          maxWidth: "4xl",
          padding: "lg",
          horizontalAlign: "center",
        },
        components: ["heading", "paragraph", "badge"],
        slots: [
          { id: "badge", name: "Badge", type: "text", required: false },
          { id: "headline", name: "Headline", type: "heading", required: true },
          { id: "subtitle", name: "Subtitle", type: "paragraph", required: true },
        ],
      },
      {
        id: "toggle",
        name: "Billing Toggle",
        nameZh: "计费周期切换",
        required: false,
        order: 2,
        layout: {
          type: "contained",
          maxWidth: "md",
          padding: "sm",
          horizontalAlign: "center",
        },
        components: ["button"],
        description: "Monthly/Annual billing toggle",
      },
      {
        id: "pricing-tiers",
        name: "Pricing Tiers",
        nameZh: "定价方案",
        required: true,
        order: 3,
        layout: {
          type: "grid",
          maxWidth: "6xl",
          columns: { mobile: 1, tablet: 2, desktop: 3 },
          padding: "lg",
          gap: "md",
          verticalAlign: "stretch",
        },
        components: ["card", "button"],
        description: "Pricing cards with features and CTAs",
      },
      {
        id: "comparison",
        name: "Feature Comparison",
        nameZh: "功能对比表",
        required: false,
        order: 4,
        layout: {
          type: "contained",
          maxWidth: "6xl",
          padding: "lg",
        },
        components: ["card"],
        description: "Detailed feature comparison table",
      },
      {
        id: "faq",
        name: "FAQ",
        nameZh: "常见问题",
        required: true,
        order: 5,
        layout: {
          type: "contained",
          maxWidth: "4xl",
          padding: "xl",
        },
        components: ["heading", "card"],
        description: "Frequently asked questions accordion",
      },
      {
        id: "cta-section",
        name: "CTA Section",
        nameZh: "行动召唤",
        required: true,
        order: 6,
        layout: {
          type: "contained",
          maxWidth: "4xl",
          padding: "xl",
          horizontalAlign: "center",
          background: "secondary",
        },
        components: ["heading", "paragraph", "button"],
      },
      {
        id: "footer",
        name: "Footer",
        nameZh: "页脚",
        required: true,
        order: 7,
        layout: { type: "contained", maxWidth: "6xl", padding: "md" },
        components: ["nav"],
      },
    ],
    responsive: {
      mobile: "Single column pricing cards. FAQ stacks vertically.",
      tablet: "2-column pricing grid. Comparison table scrolls horizontally.",
      desktop: "3-column pricing tiers. Full comparison table visible.",
    },
    tags: ["saas", "pricing", "subscription", "conversion"],
  },

  {
    id: "landing-waitlist",
    name: "Waitlist Page",
    nameZh: "等待列表页",
    category: "landing",
    description: "Minimal pre-launch page with email collection and countdown.",
    descriptionZh: "简洁预注册页面，邮箱收集 + 倒计时",
    sections: [
      {
        id: "hero",
        name: "Waitlist Hero",
        nameZh: "预注册 Hero",
        required: true,
        order: 1,
        layout: {
          type: "contained",
          maxWidth: "2xl",
          minHeight: "80vh",
          padding: "lg",
          verticalAlign: "center",
          horizontalAlign: "center",
        },
        components: ["heading", "paragraph", "input", "button", "badge"],
        slots: [
          { id: "badge", name: "Coming Soon Badge", type: "text", required: false },
          { id: "headline", name: "Headline", type: "heading", required: true },
          { id: "subtitle", name: "Subtitle", type: "paragraph", required: true },
          { id: "emailForm", name: "Email Form", type: "component", required: true },
          { id: "countdown", name: "Countdown Timer", type: "component", required: false },
        ],
      },
      {
        id: "teaser",
        name: "Feature Teaser",
        nameZh: "功能预告",
        required: false,
        order: 2,
        layout: {
          type: "grid",
          maxWidth: "4xl",
          columns: { mobile: 1, tablet: 3, desktop: 3 },
          padding: "lg",
          gap: "md",
        },
        components: ["card"],
        description: "Brief feature highlights",
      },
      {
        id: "social-proof",
        name: "Early Signups",
        nameZh: "早期注册数",
        required: false,
        order: 3,
        layout: {
          type: "contained",
          maxWidth: "md",
          padding: "md",
          horizontalAlign: "center",
        },
        components: ["badge", "paragraph"],
        description: "Number of waitlist signups or social proof",
      },
      {
        id: "footer",
        name: "Footer",
        nameZh: "页脚",
        required: true,
        order: 4,
        layout: {
          type: "contained",
          maxWidth: "4xl",
          padding: "sm",
          horizontalAlign: "center",
        },
        components: ["nav"],
        description: "Minimal footer with legal links",
      },
    ],
    responsive: {
      mobile: "Single column. Compact form. Countdown smaller.",
      tablet: "Slightly wider container. 3-column teaser.",
      desktop: "Centered max-width container. Prominent countdown.",
    },
    tags: ["prelaunch", "waitlist", "minimal", "conversion"],
  },
];
