// Portfolio Layout Archetypes

import type { LayoutArchetype } from "./types";

export const portfolioArchetypes: LayoutArchetype[] = [
  {
    id: "portfolio-gallery",
    name: "Portfolio Gallery",
    nameZh: "作品集画廊",
    category: "portfolio",
    description: "Masonry grid gallery for showcasing creative work.",
    descriptionZh: "瀑布流布局，适合展示设计作品和摄影",
    sections: [
      {
        id: "header",
        name: "Header",
        nameZh: "顶栏",
        required: true,
        order: 1,
        layout: {
          type: "contained",
          maxWidth: "7xl",
          padding: "md",
        },
        components: ["heading", "nav"],
        description: "Name/logo and navigation",
      },
      {
        id: "hero",
        name: "Portfolio Hero",
        nameZh: "作品集 Hero",
        required: false,
        order: 2,
        layout: {
          type: "contained",
          maxWidth: "4xl",
          padding: "xl",
          horizontalAlign: "center",
        },
        components: ["heading", "paragraph"],
        description: "Brief intro and tagline",
      },
      {
        id: "filters",
        name: "Category Filters",
        nameZh: "分类筛选",
        required: false,
        order: 3,
        layout: {
          type: "contained",
          maxWidth: "7xl",
          padding: "sm",
          horizontalAlign: "center",
        },
        components: ["button", "badge"],
        description: "Work category filters (All, Web, Branding, etc.)",
      },
      {
        id: "gallery",
        name: "Work Gallery",
        nameZh: "作品画廊",
        required: true,
        order: 4,
        layout: {
          type: "grid",
          maxWidth: "7xl",
          columns: { mobile: 1, tablet: 2, desktop: 3 },
          padding: "lg",
          gap: "md",
        },
        components: ["card"],
        description: "Masonry grid of portfolio pieces",
        slots: [
          { id: "items", name: "Portfolio Items", type: "list", required: true },
        ],
      },
      {
        id: "cta",
        name: "Contact CTA",
        nameZh: "联系 CTA",
        required: true,
        order: 5,
        layout: {
          type: "contained",
          maxWidth: "2xl",
          padding: "xl",
          horizontalAlign: "center",
          background: "secondary",
        },
        components: ["heading", "paragraph", "button"],
        description: "Call to action for inquiries",
      },
      {
        id: "footer",
        name: "Footer",
        nameZh: "页脚",
        required: true,
        order: 6,
        layout: {
          type: "contained",
          maxWidth: "7xl",
          padding: "md",
          horizontalAlign: "center",
        },
        components: ["nav"],
        description: "Social links and copyright",
      },
    ],
    responsive: {
      mobile: "Single column gallery. Tap to view detail.",
      tablet: "2-column masonry grid.",
      desktop: "3-column masonry. Hover effects for project info.",
    },
    tags: ["creative", "design", "photography", "showcase"],
  },

  {
    id: "portfolio-case-study",
    name: "Case Study",
    nameZh: "案例研究",
    category: "portfolio",
    description: "Detailed case study layout with full-width images and narrative.",
    descriptionZh: "全宽图片 + 详细说明，深度展示项目过程",
    sections: [
      {
        id: "header",
        name: "Header",
        nameZh: "顶栏",
        required: true,
        order: 1,
        layout: {
          type: "contained",
          maxWidth: "7xl",
          padding: "md",
        },
        components: ["nav", "button"],
        description: "Navigation with back to portfolio link",
      },
      {
        id: "hero",
        name: "Project Hero",
        nameZh: "项目 Hero",
        required: true,
        order: 2,
        layout: {
          type: "full-width",
          minHeight: "60vh",
          padding: "xl",
          verticalAlign: "center",
          horizontalAlign: "center",
          background: "accent",
        },
        components: ["heading", "paragraph", "badge"],
        description: "Project title, client, and hero image",
        slots: [
          { id: "title", name: "Project Title", type: "heading", required: true },
          { id: "client", name: "Client Name", type: "text", required: false },
          { id: "tags", name: "Project Tags", type: "list", required: false },
          { id: "heroImage", name: "Hero Image", type: "image", required: true },
        ],
      },
      {
        id: "overview",
        name: "Project Overview",
        nameZh: "项目概述",
        required: true,
        order: 3,
        layout: {
          type: "split",
          maxWidth: "6xl",
          ratio: "1:2",
          padding: "xl",
          gap: "lg",
        },
        components: ["heading", "paragraph"],
        description: "Quick stats on left, overview text on right",
      },
      {
        id: "challenge",
        name: "Challenge",
        nameZh: "挑战",
        required: true,
        order: 4,
        layout: {
          type: "contained",
          maxWidth: "4xl",
          padding: "lg",
        },
        components: ["heading", "paragraph"],
        description: "Problem statement and challenge description",
      },
      {
        id: "full-width-image",
        name: "Full Width Image",
        nameZh: "全宽图片",
        required: true,
        order: 5,
        layout: {
          type: "full-width",
          padding: "none",
        },
        components: [],
        description: "Full-width project image",
      },
      {
        id: "solution",
        name: "Solution",
        nameZh: "解决方案",
        required: true,
        order: 6,
        layout: {
          type: "contained",
          maxWidth: "4xl",
          padding: "lg",
        },
        components: ["heading", "paragraph"],
        description: "Approach and solution description",
      },
      {
        id: "gallery",
        name: "Project Gallery",
        nameZh: "项目图片",
        required: true,
        order: 7,
        layout: {
          type: "grid",
          maxWidth: "6xl",
          columns: { mobile: 1, tablet: 2, desktop: 2 },
          padding: "lg",
          gap: "md",
        },
        components: [],
        description: "Additional project images",
      },
      {
        id: "results",
        name: "Results",
        nameZh: "成果",
        required: false,
        order: 8,
        layout: {
          type: "grid",
          maxWidth: "4xl",
          columns: { mobile: 2, tablet: 4, desktop: 4 },
          padding: "xl",
          gap: "md",
          background: "secondary",
        },
        components: ["card", "heading"],
        description: "Key metrics and results",
      },
      {
        id: "testimonial",
        name: "Client Testimonial",
        nameZh: "客户评价",
        required: false,
        order: 9,
        layout: {
          type: "contained",
          maxWidth: "4xl",
          padding: "xl",
          horizontalAlign: "center",
        },
        components: ["paragraph", "heading"],
        description: "Quote from the client",
      },
      {
        id: "next-project",
        name: "Next Project",
        nameZh: "下一个项目",
        required: true,
        order: 10,
        layout: {
          type: "contained",
          maxWidth: "4xl",
          padding: "xl",
          horizontalAlign: "center",
        },
        components: ["card", "button"],
        description: "Link to next case study",
      },
      {
        id: "footer",
        name: "Footer",
        nameZh: "页脚",
        required: true,
        order: 11,
        layout: {
          type: "contained",
          maxWidth: "7xl",
          padding: "md",
        },
        components: ["nav"],
      },
    ],
    responsive: {
      mobile: "Single column. Full-width images stack.",
      tablet: "Split sections maintained. 2-column gallery.",
      desktop: "Large hero. Full narrative flow. Sticky navigation.",
    },
    tags: ["case-study", "project", "detailed", "narrative"],
  },
];
