/**
 * PR Lint Comment Generator
 *
 * Generates a markdown PR comment from StyleKit lint results.
 * Reads lint JSON output from stdin or a file and produces
 * a formatted markdown summary suitable for posting as a PR comment.
 *
 * Usage:
 *   npx tsx tools/scripts/pr-lint-comment.ts --input lint-results.json
 */

import { readFileSync } from "fs";

interface LintViolation {
  class: string;
  severity: "error" | "warning";
  reason: string;
  line: number | null;
}

interface FileLintOutput {
  file: string;
  valid: boolean;
  errors: number;
  warnings: number;
  violations: LintViolation[];
  fixes: string[];
}

interface LintJsonOutput {
  style: string;
  totalFiles: number;
  totalErrors: number;
  totalWarnings: number;
  files: FileLintOutput[];
}

function generatePRComment(data: LintJsonOutput): string {
  const lines: string[] = [];
  const totalViolations = data.totalErrors + data.totalWarnings;
  const passRate = data.totalFiles > 0
    ? Math.round(((data.totalFiles - data.files.filter(f => !f.valid).length) / data.totalFiles) * 100)
    : 100;

  // Header
  if (data.totalErrors === 0) {
    lines.push("## StyleKit Lint: PASS");
  } else {
    lines.push("## StyleKit Lint: FAIL");
  }

  lines.push("");

  // Summary
  lines.push(`**Style:** \`${data.style}\`  `);
  lines.push(`**Files checked:** ${data.totalFiles}  `);
  lines.push(`**Errors:** ${data.totalErrors}  `);
  lines.push(`**Warnings:** ${data.totalWarnings}  `);
  lines.push(`**Compliance:** ${passRate}%`);
  lines.push("");

  if (totalViolations === 0) {
    lines.push("All files comply with the style guidelines.");
    return lines.join("\n");
  }

  // Violations table
  lines.push("### Violations");
  lines.push("");
  lines.push("| File | Line | Class | Severity | Reason |");
  lines.push("|------|------|-------|----------|--------|");

  for (const file of data.files) {
    if (file.violations.length === 0) continue;
    for (const v of file.violations) {
      const severity = v.severity === "error" ? "ERROR" : "WARN";
      const line = v.line !== null ? String(v.line) : "-";
      lines.push(`| \`${file.file}\` | ${line} | \`${v.class}\` | ${severity} | ${v.reason} |`);
    }
  }

  lines.push("");

  // Suggested fixes
  const filesWithFixes = data.files.filter(f => f.fixes.length > 0);
  if (filesWithFixes.length > 0) {
    lines.push("### Suggested Fixes");
    lines.push("");
    for (const file of filesWithFixes) {
      lines.push(`**\`${file.file}\`**`);
      for (const fix of file.fixes) {
        lines.push(`- ${fix}`);
      }
      lines.push("");
    }
  }

  // Footer
  lines.push("---");
  lines.push(`*Generated by [StyleKit Lint](https://github.com/anthropics/stylekit) | Style: \`${data.style}\` | Compliance: ${passRate}%*`);

  return lines.join("\n");
}

// ---- Main ----

function main(): void {
  const args = process.argv.slice(2);
  let input: string;

  const inputIndex = args.indexOf("--input");
  if (inputIndex !== -1 && args[inputIndex + 1]) {
    input = readFileSync(args[inputIndex + 1], "utf-8");
  } else {
    // Read from stdin
    input = readFileSync("/dev/stdin", "utf-8");
  }

  let data: LintJsonOutput;
  try {
    data = JSON.parse(input);
  } catch {
    console.error("Error: Invalid JSON input. Pass a lint-results.json file with the expected schema.");
    process.exit(1);
  }

  console.log(generatePRComment(data));
}

main();
